import { useEffect, useMemo, useState } from 'react';
import { ArrowLeft, Calculator, Check, FileText, X } from 'lucide-react';
import { Field, inputCls } from '@/components/Field';
import { buildActivityIndex, suggestActivities, type ActivityCandidate } from '@/services/activiteMatcher';

interface DecisionRow { rubrique: string; criterion: string; rawCondition: string; min?: number | null; minInclusive?: boolean; max?: number | null; maxInclusive?: boolean; unit?: string; regime: string; rayon?: string; documents?: { impact?: boolean; danger?: boolean; notice?: boolean; rapportDangereux?: boolean }; sourcePage?: number }
interface Row { rubrique: string; famille: string; familleLabel: string; designation: string; decisionRows?: DecisionRow[]; source: string; sourceUrl: string }
interface Dataset { version: string; date: string; sourceUrl: string; rubriques: Row[] }
interface Accepted extends ActivityCandidate { id: string; row: Row }
const EMPTY: Dataset = { version: '07-144', date: '19 mai 2007', sourceUrl: 'https://www.joradp.dz/FTP/jo-francais/2007/F2007034.PDF', rubriques: [] };
function clean(v:string){return v.replace(/Ã©/g,'é').replace(/Ã¨/g,'è').replace(/Ãª/g,'ê').replace(/Ã®/g,'î').replace(/Ã´/g,'ô').replace(/Ã¹/g,'ù').replace(/Ã§/g,'ç').replace(/Ã /g,'à').replace(/â€™/g,'’').replace(/dâ€™/g,'d’').replace(/lâ€™/g,'l’').replace(/\s+/g,' ').trim();}
function displayDesignation(value:string){const text=clean(value);const markers=[/\bLa quantité totale susceptible d[’']être présente/i,/\bLa capacité de production étant/i,/\bLa puissance installée/i,/\bLe volume total/i,/\bLe volume susceptible d[’']être stocké/i,/\bLorsque la quantité/i,/\bLorsque la capacité/i,/\bLorsque le nombre/i,/\bLa quantité de matière/i,/\b1\.\s+/];let cut=text.length;for(const marker of markers){const i=text.search(marker);if(i>8)cut=Math.min(cut,i);}return text.slice(0,cut).replace(/[;:,-]+\s*$/,'').trim();}
function norm(v:string){return v.toLocaleLowerCase('fr-FR').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[’'`´]/g,' ').replace(/[^\p{L}\p{N}]+/gu,' ').replace(/\s+/g,' ').trim();}
function num(v:string){const n=Number(String(v).replace(/\s/g,'').replace(/\.(?=\d{3}(?:\D|$))/g,'').replace(',','.'));return Number.isFinite(n)?n:null;}
function matches(r:DecisionRow,value:number){return (r.min==null||(r.minInclusive===false?value>r.min:value>=r.min))&&(r.max==null||(r.maxInclusive===false?value<r.max:value<=r.max));}
function range(r:DecisionRow){const u=r.unit?` ${r.unit}`:'';if(r.min!=null&&r.max!=null)return `${r.minInclusive===false?'>':'≥'} ${r.min}${u} et ${r.maxInclusive===false?'<':'≤'} ${r.max}${u}`;if(r.min!=null)return `${r.minInclusive===false?'>':'≥'} ${r.min}${u}`;if(r.max!=null)return `${r.maxInclusive===false?'<':'≤'} ${r.max}${u}`;return r.rawCondition;}
function regimeLabel(v:string){return ({AM:'Autorisation ministérielle',AW:'Autorisation du Wali',APAPC:'Autorisation du président de l’APC',D:'Déclaration auprès du président de l’APC'} as Record<string,string>)[v]??v;}
function category(v:string){return ({AM:'1re catégorie',AW:'2e catégorie',APAPC:'3e catégorie',D:'4e catégorie'} as Record<string,string>)[v]??'';}
function directRubrique(query:string,rows:Row[]){const m=norm(query).match(/^([12]\d{3})$/);return m?(rows.find(r=>r.rubrique===m[1])??null):null;}
function docsFrom(row:DecisionRow){return [['Étude d’impact',!!row.documents?.impact],['Étude de dangers',!!row.documents?.danger],['Notice d’impact',!!row.documents?.notice],['Rapport sur les produits dangereux',!!row.documents?.rapportDangereux]] as const;}

export function EnvironnementPageV9({clientName,dossierNumero,onBack}:{clientName:string;dossierNumero?:string;onBack:()=>void}){
 const [dataset,setDataset]=useState<Dataset>(EMPTY); const [query,setQuery]=useState(''); const [accepted,setAccepted]=useState<Accepted|null>(null); const [value,setValue]=useState(''); const [result,setResult]=useState<DecisionRow|null>(null); const [error,setError]=useState('');
 useEffect(()=>{fetch('/data/nomenclature-07-144.json').then(async r=>{if(!r.ok)throw new Error(`HTTP ${r.status}`);return await r.json() as Dataset;}).then(d=>setDataset({...d,rubriques:(d.rubriques??[]).map(r=>({...r,designation:clean(r.designation),familleLabel:clean(r.familleLabel)}))})).catch(e=>setError((e as Error).message));},[]);
 const index=useMemo(()=>buildActivityIndex(dataset.rubriques),[dataset.rubriques]); const direct=useMemo(()=>directRubrique(query,dataset.rubriques),[query,dataset.rubriques]); const suggestions=useMemo(()=>accepted||direct||query.trim().length<2?[]:suggestActivities(index,query,10),[accepted,direct,index,query]);
 const row=accepted?.row??direct; const decisionRows=row?.decisionRows??[]; const firstCriterion=decisionRows[0]?.criterion??''; const firstUnit=decisionRows[0]?.unit??''; const hasNumeric=decisionRows.some(r=>r.min!=null||r.max!=null);
 function reset(){setQuery('');setAccepted(null);setValue('');setResult(null);setError('');}
 function acceptRow(r:Row,candidate?:ActivityCandidate){const c=candidate??{rubrique:r.rubrique,famille:r.famille,familleLabel:r.familleLabel,designation:r.designation,score:1000,matchedTerms:[],source:r.source};setAccepted({...c,id:`${r.rubrique}|${r.designation}`,row:r});setValue('');setResult(null);}
 function calculate(){if(!row)return;if(!decisionRows.length){setError('Aucune ligne de décision structurée n’est disponible pour cette rubrique.');setResult(null);return;}if(!hasNumeric){setResult(decisionRows[0]);setError('');return;}const n=num(value);if(n==null){setError('Veuillez saisir une valeur numérique valide.');setResult(null);return;}const matched=decisionRows.find(r=>matches(r,n));if(!matched){setError('La valeur saisie ne correspond à aucun intervalle de cette rubrique dans la nomenclature 07-144.');setResult(null);return;}setError('');setResult(matched);}
 return <div className="space-y-6"><div className="flex items-center justify-between gap-3"><div className="flex items-center gap-3"><button type="button" onClick={onBack} className="p-2 rounded-lg border border-gray-300 hover:bg-gray-50"><ArrowLeft size={18}/></button><div><h1 className="text-2xl font-bold text-gray-800">Module Environnement</h1><p className="text-sm text-gray-500">{dossierNumero??'Nouveau projet'}{clientName?` — ${clientName}`:''}</p></div></div><span className="text-xs px-3 py-1.5 rounded-full bg-emerald-50 text-emerald-700 border border-emerald-200">Nomenclature 07-144</span></div>
 <div className="grid grid-cols-3 gap-2 text-xs"><Step n="1" title="Rubrique" active={!row}/><Step n="2" title="Classement" active={!!row&&!result}/><Step n="3" title="Dossier réglementaire" active={!!result}/></div>
 {!row&&<div className="bg-white rounded-xl border border-gray-200 shadow-sm p-5"><Field label="Type / désignation de l’activité" required><div className="relative"><input className={`${inputCls} pr-10`} value={query} onChange={e=>{setQuery(e.target.value);setError('');}} placeholder="Désignation de l’activité ou N° de rubrique (ex. 1240)"/>{query&&<button type="button" onClick={reset} className="absolute top-2.5 right-2.5 p-1.5 text-gray-400 hover:text-red-600"><X size={16}/></button>}</div></Field>
 {direct&&<div className="mt-4 border border-emerald-200 bg-emerald-50 rounded-lg p-4 flex items-center gap-3"><div className="flex-1"><div className="text-sm font-semibold">Rubrique {direct.rubrique}</div><div className="text-sm text-gray-800 mt-1">{displayDesignation(direct.designation)}</div></div><button type="button" onClick={()=>acceptRow(direct)} className="inline-flex items-center gap-1 px-3 py-1.5 rounded-lg bg-emerald-600 text-white text-xs font-semibold"><Check size={14}/> Accepter</button></div>}
 {!direct&&query.trim().length>=2&&<div className="mt-4"><div className="text-xs font-semibold text-gray-500 mb-2">Rubriques / activités suggérées — par ordre de correspondance</div>{suggestions.length?<div className="border rounded-lg divide-y max-h-96 overflow-y-auto">{suggestions.map((c,i)=><div key={`${c.rubrique}-${c.designation}`} className="p-4 flex items-center gap-3"><div className="w-10 text-xs font-bold text-gray-400">#{i+1}</div><div className="flex-1"><div className="font-medium text-sm">Rubrique {c.rubrique}</div><div className="text-sm text-gray-800 mt-1">{displayDesignation(c.designation)}</div></div><button type="button" onClick={()=>acceptRow(dataset.rubriques.find(r=>r.rubrique===c.rubrique)??({rubrique:c.rubrique,famille:c.famille,familleLabel:c.familleLabel,designation:c.designation,source:c.source,sourceUrl:dataset.sourceUrl} as Row),c)} className="inline-flex items-center gap-1 px-3 py-1.5 rounded-lg bg-emerald-600 text-white text-xs font-semibold"><Check size={14}/> Accepter</button></div>)}</div>:<div className="rounded-lg bg-amber-50 border border-amber-200 p-3 text-sm text-amber-800">Aucune proposition suffisamment fiable.</div>}</div>}</div>}
 {row&&<><div className="bg-white rounded-xl border border-emerald-200 shadow-sm p-5"><div className="text-sm font-semibold text-emerald-800">Rubrique sélectionnée</div><div className="text-xl font-bold mt-1">{row.rubrique}</div><div className="text-sm text-gray-700 mt-1">{displayDesignation(row.designation)}</div><button type="button" onClick={reset} className="mt-3 text-xs text-sky-700 hover:underline">Changer</button></div>
 <div className="bg-white rounded-xl border border-gray-200 shadow-sm p-5"><div className="flex items-center gap-2 mb-4"><Calculator size={18} className="text-emerald-600"/><h2 className="font-semibold">Donnée nécessaire au classement</h2></div>{decisionRows.length?<><div className="rounded-lg bg-slate-50 border border-slate-200 p-4 mb-4"><div className="text-sm font-semibold">{firstCriterion||'Valeur de classement'}</div><div className="text-xs text-gray-500 mt-1">{firstUnit?`Unité : ${firstUnit}`:'Selon la rubrique'}</div></div>{hasNumeric&&<Field label={firstUnit?`${firstCriterion} (${firstUnit})`:firstCriterion||'Valeur'} required><input className={inputCls} type="number" min="0" value={value} onChange={e=>{setValue(e.target.value);setResult(null);setError('');}}/></Field>}{!hasNumeric&&<div className="text-sm text-gray-600">Cette rubrique ne demande pas de valeur numérique pour son classement.</div>}<button type="button" onClick={calculate} disabled={hasNumeric&&!value.trim()} className="mt-5 inline-flex items-center gap-2 px-4 py-2 rounded-lg bg-sky-600 text-white text-sm font-semibold disabled:opacity-40"><Calculator size={16}/> Calculer le classement</button></>:<div className="rounded-lg bg-amber-50 border border-amber-200 p-4 text-sm text-amber-800">Aucune donnée de classement structurée n’est disponible pour cette rubrique.</div>}</div>
 {result&&<><div className="bg-emerald-50 border border-emerald-200 rounded-xl p-5"><div className="text-sm font-semibold text-emerald-800">Classement selon la Nomenclature 07-144</div><div className="text-2xl font-bold text-emerald-950 mt-1">{category(result.regime)} — {regimeLabel(result.regime)}</div><div className="grid md:grid-cols-4 gap-3 mt-4"><Result label="Rubrique" value={result.rubrique}/><Result label="Intervalle retenu" value={range(result)}/><Result label="Rayon d’affichage" value={result.rayon||'—'}/><Result label="Régime" value={result.regime}/></div></div><div className="bg-white rounded-xl border border-gray-200 shadow-sm p-5"><div className="flex items-center gap-2 mb-4"><FileText size={18} className="text-emerald-600"/><h2 className="font-semibold">Dossier réglementaire — documents marqués X</h2></div><div className="grid md:grid-cols-2 gap-3">{docsFrom(result).map(([name,required])=><div key={name} className={`rounded-lg border p-4 ${required?'bg-emerald-50 border-emerald-200':'bg-gray-50 border-gray-200'}`}><div className="text-xs font-semibold">{required?'REQUIS — X':'Non requis'}</div><div className="font-medium mt-1">{name}</div></div>)}</div></div></>}
 </>}{error&&<div className="bg-red-50 border border-red-200 text-red-700 rounded-lg p-3 text-sm">{error}</div>}</div>;
}
function Step({n,title,active}:{n:string;title:string;active:boolean}){return <div className={`rounded-lg border p-2 text-center ${active?'border-emerald-300 bg-emerald-50 text-emerald-800':'border-gray-200 bg-gray-50 text-gray-500'}`}>{n}. {title}</div>}
function Result({label,value}:{label:string;value:string}){return <div className="rounded-lg border border-emerald-100 bg-white/70 p-3"><div className="text-xs text-emerald-700">{label}</div><div className="font-semibold mt-1">{value}</div></div>}
