import { useEffect, useState } from 'react';
import type { Client } from '@/types';
import type { Feature, Geometry, Position } from 'geojson';
import L from 'leaflet';
import { TopographiePage } from './TopographiePage';
import { CadastralPlanSheet, type CadastralAdmin, type CadastralNeighbor } from '../components/CadastralPlanSheet';
import { Demande4300Page } from '../components/Demande4300Page';

type Props=Record<string,unknown>; type Parcel=Feature<Geometry,Props>; type Bounds={minX:number;maxX:number;minY:number;maxY:number};
const STORE:Parcel[]=[];let hooked=false;
const text=(v:unknown)=>String(v??'').trim(),digits=(v:unknown)=>text(v).replace(/[^0-9]/g,'');
const prop=(p:Props,keys:string[])=>{for(const k of keys){const v=p[k];if(v!==undefined&&v!==null&&text(v)!=='')return text(v)}return''};
const sectionOf=(p:Props)=>prop(p,['se_no','se_no_nat','section','SECTION','section_no','SECTION_NO','numero_section','NUMERO_SECTION']);
const ilotOf=(p:Props)=>prop(p,['il_no','il_no_nat','ilot','ILOT','ilot_no','ILOT_NO','numero_ilot','NUMERO_ILOT']);
const areaOf=(p:Props)=>prop(p,['SHAPE_Area','SHAPE__Area','il_surf_de','il_surf_ca','surface','SURFACE','area','AREA','superficie','SUPERFICIE']);
const communeOf=(p:Props)=>prop(p,['commune','COMMUNE','municipality','MUNICIPALITE','municipalite','Municipalite']);
const dairaOf=(p:Props)=>prop(p,['daira','DAIRA','daira_name','DAIRA_NAME']);
const wilayaOf=(p:Props)=>prop(p,['wilaya','WILAYA','province','PROVINCE']);
const DAIRA_BY_COMMUNE:Record<string,string>={'Ain Touila':'Ain Touila',"M'Toussa":'Ain Touila','Babar':'Babar','Bouhmama':'Bouhmama','Chelia':'Bouhmama',"M'Sara":'Bouhmama','Yabous':'Bouhmama','Chechar':'Chechar','Djellal':'Chechar','El Ouldja':'Chechar','Khirane':'Chechar','Khenchela':'Khenchela','El Hamma':'El Hamma','Baghai':'El Hamma','Ensigha':'El Hamma','Tamza':'El Hamma','Kais':'Kais','Remila':'Kais','Taouzianat':'Kais','Ouled Rechache':'Ouled Rechache','El Mahmal':'Ouled Rechache'};
const ringOf=(g:Geometry):Position[]=>g.type==='Polygon'?(g.coordinates[0]??[]):g.type==='LineString'?(g.coordinates??[]):[];
const bounds=(r:Position[]):Bounds=>{const xs=r.map(p=>+p[0]),ys=r.map(p=>+p[1]);return{minX:Math.min(...xs),maxX:Math.max(...xs),minY:Math.min(...ys),maxY:Math.max(...ys)}};
const dist=(a:Bounds,b:Bounds)=>{let dx=0,dy=0;if(a.maxX<b.minX)dx=b.minX-a.maxX;else if(b.maxX<a.minX)dx=a.minX-b.maxX;if(a.maxY<b.minY)dy=b.minY-a.maxY;else if(b.maxY<a.minY)dy=a.minY-b.maxY;return Math.hypot(dx,dy)};
const capture=(x:unknown)=>{const f=x as Parcel;if(!f?.geometry||!f.properties)return;const k=`${String(f.id??'')}-${sectionOf(f.properties)}-${ilotOf(f.properties)}`;if(!STORE.some(z=>`${String(z.id??'')}-${sectionOf(z.properties??{})}-${ilotOf(z.properties??{})}`===k))STORE.push(f)};
function rememberLayer(layer:any,feature:Parcel){if(!layer||!feature)return;layer.__urbatecParcel=feature;layer.on?.('click',()=>{(window as any).__urbatecSelectedParcel=feature;window.dispatchEvent(new CustomEvent('urbatec:parcel-selected',{detail:feature}))})}
function install(){if(hooked)return;hooked=true;const p=L.GeoJSON.prototype as any,o=p.addData;p.addData=function(data:any){const result=o.call(this,data);if(data?.type==='FeatureCollection'&&Array.isArray(data.features)){data.features.forEach(capture);const layers=this.getLayers?.()??[];data.features.forEach((f:any)=>{const layer=layers.find((l:any)=>l.feature===f);if(layer)rememberLayer(layer,f)})}else if(data?.type==='Feature'){capture(data);const layer=(this.getLayers?.()??[]).find((l:any)=>l.feature===data);if(layer)rememberLayer(layer,data)}return result}};
install();
function readDomValue(patterns:RegExp[],root:ParentNode=document):string{const body=(root as Document|HTMLElement).textContent||'';for(const re of patterns){const m=body.match(re);if(m?.[1]?.trim())return m[1].trim()}return''}
function selectedFromDom(){const remembered=(window as any).__urbatecSelectedParcel as Parcel|null|undefined;if(remembered?.geometry&&remembered?.properties)return remembered;const popup=document.querySelector('.leaflet-popup-content');const roots:ParentNode[]=[popup??document];const sectionPatterns=[/Section\s*(?:numero|n°|N°|No)?\s*[:\-]?\s*([^\n|]+)/i,/Section\s*[:\-]\s*([^\n|]+)/i];const ilotPatterns=[/Ilot\s*(?:numero|n°|N°|No)?\s*[:\-]?\s*([^\n|]+)/i,/Ilot\s*[:\-]\s*([^\n|]+)/i];for(const root of roots){const ss=digits(readDomValue(sectionPatterns,root)),ii=digits(readDomValue(ilotPatterns,root));if(ss&&ii){const exact=STORE.find(f=>digits(sectionOf(f.properties??{}))===ss&&digits(ilotOf(f.properties??{}))===ii);if(exact)return exact}}const inputs=Array.from(document.querySelectorAll<HTMLInputElement>('input,select'));const sectionInput=inputs.find(e=>/section/i.test(`${e.name} ${e.id} ${e.placeholder} ${e.getAttribute('aria-label')||''}`));const ilotInput=inputs.find(e=>/ilot|îlot/i.test(`${e.name} ${e.id} ${e.placeholder} ${e.getAttribute('aria-label')||''}`));const s2=digits(sectionInput?.value),i2=digits(ilotInput?.value);if(s2&&i2){const exact=STORE.find(f=>digits(sectionOf(f.properties??{}))===s2&&digits(ilotOf(f.properties??{}))===i2);if(exact)return exact}return STORE.length===1?STORE[0]:null}
function currentCommune(){const el=document.querySelector<HTMLInputElement>('input[placeholder*="Commune"],select[name*="commune" i],input[name*="commune" i]');return text(el?.value)}
function adminFor(p:Parcel):CadastralAdmin{const pr=p.properties??{},c=text(communeOf(pr)||currentCommune()||'Khenchela');return{commune:c,daira:text(dairaOf(pr)||DAIRA_BY_COMMUNE[c]||'—'),wilaya:text(wilayaOf(pr)||'Khenchela')}}

export function TopographieWithPlanPreviewLite({clients,onUpdateClient}:{clients:Client[];onUpdateClient:(id:string,data:Partial<Client>)=>Promise<void>}){
 const[open,setOpen]=useState(false),[selected,setSelected]=useState<Parcel|null>(null),[neighbors,setNeighbors]=useState<CadastralNeighbor[]>([]),[admin,setAdmin]=useState<CadastralAdmin>({commune:'Khenchela',daira:'—',wilaya:'Khenchela'}),[demandeOpen,setDemandeOpen]=useState(false);
 useEffect(()=>{const onSelected=(e:Event)=>{const p=(e as CustomEvent<Parcel>).detail;if(p?.geometry){setSelected(p);setAdmin(adminFor(p))}};window.addEventListener('urbatec:parcel-selected',onSelected);const onClick=(e:MouseEvent)=>{const btn=(e.target as HTMLElement|null)?.closest('button');if(!btn)return;const label=btn.textContent?.toLowerCase()||'';
   if(label.includes('demande 4300')){e.preventDefault();e.stopPropagation();const p=selectedFromDom();if(p){setSelected(p);setAdmin(adminFor(p));}setDemandeOpen(true);return;}
   if(!label.includes('extrait du plan'))return;
   const p=selectedFromDom();if(!p)return;const r=ringOf(p.geometry);if(r.length<3)return;const b=bounds(r);const near=STORE.filter(f=>f!==p).map(f=>({f,r:ringOf(f.geometry)})).filter(x=>x.r.length>2).map(x=>({...x,d:dist(b,bounds(x.r))})).sort((a,b)=>a.d-b.d).slice(0,4).map((x,i)=>({id:String(x.f.id??i),ilot:ilotOf(x.f.properties??{})||`N${i+1}`,section:sectionOf(x.f.properties??{})||undefined,coordinates:x.r}));setSelected(p);setNeighbors(near);setAdmin(adminFor(p));setOpen(true)};document.addEventListener('click',onClick,true);return()=>{window.removeEventListener('urbatec:parcel-selected',onSelected);document.removeEventListener('click',onClick,true)}},[]);
 const pr=selected?.properties??{};const demandeParcel=selected?{...selected,properties:{...(selected.properties??{}),...(admin.commune?{commune:admin.commune}:{}),...(admin.daira?{daira:admin.daira}:{}),...(admin.wilaya?{wilaya:admin.wilaya}:{})}}:null;
 const overlayStyle:React.CSSProperties={position:'fixed',inset:'6vh 8vw',zIndex:10000,maxWidth:'1100px',margin:'0 auto',background:'rgba(255,255,255,.93)',border:'1px solid rgba(148,163,184,.50)',borderRadius:'12px',boxShadow:'0 20px 60px rgba(15,23,42,.26)',overflow:'hidden',display:'flex',flexDirection:'column',backdropFilter:'blur(10px)'};
 return <><TopographiePage/><div style={{display:open?'block':'none',position:'fixed',inset:0,zIndex:9998,background:'rgba(15,23,42,.16)',backdropFilter:'blur(2px)'}}><div style={{position:'fixed',inset:'10px',overflow:'auto',background:'#fff',borderRadius:'12px',boxShadow:'0 18px 55px rgba(0,0,0,.25)'}}><CadastralPlanSheet open={true} onClose={()=>setOpen(false)} commune={admin.commune} admin={admin} section={sectionOf(pr)} ilot={ilotOf(pr)} surface={areaOf(pr)} selectedRing={selected?ringOf(selected.geometry):[]} neighbors={neighbors}/></div></div><div style={{display:demandeOpen?'flex':'none',position:'fixed',inset:0,zIndex:10000,background:'rgba(15,23,42,.20)',backdropFilter:'blur(3px)',padding:'0',alignItems:'center',justifyContent:'center'}}><div style={overlayStyle}><div style={{position:'sticky',top:0,zIndex:20,flex:'0 0 auto',background:'rgba(255,255,255,.84)',backdropFilter:'blur(12px)',borderBottom:'1px solid rgba(148,163,184,.30)',padding:'6px 8px',display:'flex',justifyContent:'flex-end',boxShadow:'0 2px 10px rgba(15,23,42,.06)'}}><button type="button" onClick={()=>setDemandeOpen(false)} aria-label="Fermer" style={{border:'1px solid rgba(148,163,184,.65)',borderRadius:'8px',background:'rgba(255,255,255,.88)',padding:'5px 11px',fontWeight:700,cursor:'pointer',boxShadow:'0 2px 5px rgba(15,23,42,.08)'}}>← Retour</button></div><div style={{flex:'1 1 auto',minHeight:0,overflow:'auto',padding:'0 4px 6px'}}><Demande4300Page clients={clients} onUpdateClient={onUpdateClient} parcel={demandeParcel} parcelAdmin={admin} onClose={()=>setDemandeOpen(false)}/></div></div></div></>;
}