import { useEffect, useState } from 'react';
import type { Feature, FeatureCollection, Geometry, Position } from 'geojson';
import L from 'leaflet';
import { TopographiePage } from './TopographiePage';
import { CadastralPlanPreviewAccurate, type CadastralAdminAccurate as Admin, type CadastralNeighborAccurate as Neighbor } from '../components/CadastralPlanPreviewAccurate';

type Props=Record<string,unknown>; type Parcel=Feature<Geometry,Props>; type Bounds={minX:number;maxX:number;minY:number;maxY:number};
const COLLECTIONS:FeatureCollection<Geometry>[]=[]; let installed=false;
const text=(v:unknown)=>String(v??'').trim(); const digits=(v:unknown)=>text(v).replace(/[^0-9]/g,'');
const prop=(p:Props,keys:string[])=>{for(const k of keys){const v=p[k];if(v!==undefined&&v!==null&&text(v)!=='')return text(v)}return''};
const sectionOf=(p:Props)=>prop(p,['se_no','se_no_nat','section','SECTION']); const ilotOf=(p:Props)=>prop(p,['il_no','il_no_nat','ilot','ILOT']); const areaOf=(p:Props)=>prop(p,['SHAPE_Area','il_surf_de','il_surf_ca','area','AREA']);
const communeOf=(p:Props)=>prop(p,['commune','COMMUNE','municipality','MUNICIPALITE']); const dairaOf=(p:Props)=>prop(p,['daira','DAIRA']); const wilayaOf=(p:Props)=>prop(p,['wilaya','WILAYA','province','PROVINCE']);
const DAIRA:Record<string,string>={'Ain Touila':'Ain Touila',"M'Toussa":'Ain Touila','Babar':'Babar','Bouhmama':'Bouhmama','Chelia':'Bouhmama','Chechar':'Chechar','Djellal':'Chechar','El Ouldja':'Chechar','Khirane':'Chechar','Khenchela':'Khenchela','El Hamma':'El Hamma','Baghai':'El Hamma','Ensigha':'El Hamma','Tamza':'El Hamma','Kais':'Kais','Remila':'Kais','Taouzianat':'Kais','Ouled Rechache':'Ouled Rechache','El Mahmal':'Ouled Rechache','Yabous':'Bouhmama'};
const norm=(v:string)=>v.trim().replace(/\s+/g,' ').replace(/’/g,"'");
function installLazy(){if(installed)return;installed=true;const proto=L.GeoJSON.prototype as any,original=proto.addData;proto.addData=function(data:any){if(data?.type==='FeatureCollection'&&!COLLECTIONS.includes(data))COLLECTIONS.push(data);else if(data?.type==='Feature')COLLECTIONS.push({type:'FeatureCollection',features:[data]});return original.call(this,data)}}
installLazy();
function ring(g:Geometry):Position[]{return g.type==='Polygon'?(g.coordinates[0]??[]):g.type==='LineString'?(g.coordinates??[]):[];}
function bounds(r:Position[]):Bounds{const xs=r.map(p=>+p[0]),ys=r.map(p=>+p[1]);return{minX:Math.min(...xs),maxX:Math.max(...xs),minY:Math.min(...ys),maxY:Math.max(...ys)}}
function dist(a:Bounds,b:Bounds){const dx=a.maxX<b.minX?b.minX-a.maxX:b.maxX<a.minX?a.minX-b.maxX:0,dy=a.maxY<b.minY?b.minY-a.maxY:a.minY-b.maxY:0;return Math.hypot(dx,dy)}
function clip(r:Position[],box:Bounds){const c=(pts:Position[],inside:(p:Position)=>boolean,ix:(a:Position,b:Position)=>Position)=>{const o:Position[]=[];let prev=pts[pts.length-1],pin=inside(prev);for(const cur of pts){const cin=inside(cur);if(cin&&!pin)o.push(ix(prev,cur));if(cin)o.push(cur);else if(pin)o.push(ix(prev,cur));prev=cur;pin=cin}return o};let o=r.slice();o=c(o,p=>+p[0]>=box.minX,(a,b)=>{const t=(box.minX-+a[0])/(+b[0]-+a[0]||1);return[box.minX,+a[1]+(+b[1]-+a[1])*t]});o=c(o,p=>+p[0]<=box.maxX,(a,b)=>{const t=(box.maxX-+a[0])/(+b[0]-+a[0]||1);return[box.maxX,+a[1]+(+b[1]-+a[1])*t]});o=c(o,p=>+p[1]>=box.minY,(a,b)=>{const t=(box.minY-+a[1])/(+b[1]-+a[1]||1);return[+a[0]+(+b[0]-+a[0])*t,box.minY]});o=c(o,p=>+p[1]<=box.maxY,(a,b)=>{const t=(box.maxY-+a[1])/(+b[1]-+a[1]||1);return[+a[0]+(+b[0]-+a[0])*t,box.maxY]});return o}
function currentCommune(){return norm(document.querySelector<HTMLInputElement>('input[placeholder*="Commune"]')?.value??'')}
function selectedFromInfo():Parcel|null{const body=document.body.innerText,sm=body.match(/Section numero\s*:\s*([^\n]+)/i),im=body.match(/Ilot numero\s*:\s*([^\n]+)/i);if(!sm||!im)return null;const s=digits(sm[1]),i=digits(im[1]);for(const fc of COLLECTIONS){const f=fc.features.find(x=>digits(sectionOf((x.properties??{}) as Props))===s&&digits(ilotOf((x.properties??{}) as Props))===i);if(f)return f as Parcel}return null}
function adminOf(p:Parcel):Admin{const props=(p.properties??{}) as Props,commune=norm(communeOf(props)||currentCommune()||'Khenchela');return{commune,daira:norm(dairaOf(props)||DAIRA[commune]||'—'),wilaya:norm(wilayaOf(props)||'Khenchela')};}
export function TopographieWithPlanPreview(){const[open,setOpen]=useState(false),[selected,setSelected]=useState<Parcel|null>(null),[neighbors,setNeighbors]=useState<Neighbor[]>([]),[admin,setAdmin]=useState<Admin>({commune:'Khenchela',daira:'—',wilaya:'Khenchela'});
 useEffect(()=>{const click=(e:MouseEvent)=>{const button=(e.target as HTMLElement|null)?.closest('button');if(!button||!button.textContent?.toLowerCase().includes('extrait du plan'))return;const parcel=selectedFromInfo();if(!parcel)return;const r=ring(parcel.geometry);if(r.length<3)return;const sb=bounds(r),px=Math.max(.0002,(sb.maxX-sb.minX)*.28),py=Math.max(.0002,(sb.maxY-sb.minY)*.28),box={minX:sb.minX-px,maxX:sb.maxX+px,minY:sb.minY-py,maxY:sb.maxY+py},sec=digits(sectionOf((parcel.properties??{}) as Props));const c:{f:Parcel;r:Position[];d:number}[]=[];for(const fc of COLLECTIONS)for(const x of fc.features){const f=x as Parcel;if(f===parcel||digits(sectionOf((f.properties??{}) as Props))!==sec)continue;const rr=ring(f.geometry);if(rr.length>=3)c.push({f,r:rr,d:dist(sb,bounds(rr))})}c.sort((a,b)=>a.d-b.d);const ns=c.slice(0,4).map((x,i)=>({id:`n${i}`,ilot:ilotOf((x.f.properties??{}) as Props)||`N${i+1}`,section:sectionOf((x.f.properties??{}) as Props)||undefined,coordinates:clip(x.r,box)})).filter(n=>n.coordinates.length>=2);setSelected(parcel);setNeighbors(ns);setAdmin(adminOf(parcel));setOpen(true)};document.addEventListener('click',click);return()=>document.removeEventListener('click',click)},[]);
 const props=(selected?.properties??{}) as Props;return<><TopographiePage/><CadastralPlanPreviewAccurate open={open} onClose={()=>setOpen(false)} admin={admin} section={sectionOf(props)} ilot={ilotOf(props)} surface={areaOf(props)} selectedRing={selected?ring(selected.geometry):[]} neighbors={neighbors}/></>;
}
