import { useEffect, useState } from 'react';
import type { Feature, FeatureCollection, Geometry, Position } from 'geojson';
import L from 'leaflet';
import { TopographiePage } from './TopographiePage';
import { CadastralPlanPreviewLight, type CadastralAdminLight, type CadastralNeighborLight } from '../components/CadastralPlanPreviewLight';

type Props=Record<string,unknown>; type Parcel=Feature<Geometry,Props>; type Bounds={minX:number;maxX:number;minY:number;maxY:number};
const COLLECTIONS:FeatureCollection<Geometry>[]=[]; let installed=false;
const textOf=(v:unknown)=>String(v??'').trim(); const digits=(v:unknown)=>textOf(v).replace(/[^0-9]/g,'');
const prop=(p:Props,keys:string[])=>{for(const k of keys){const v=p[k];if(v!==undefined&&v!==null&&textOf(v)!=='')return textOf(v)}return''};
const sectionOf=(p:Props)=>prop(p,['se_no','se_no_nat','section','SECTION']); const ilotOf=(p:Props)=>prop(p,['il_no','il_no_nat','ilot','ILOT']); const areaOf=(p:Props)=>prop(p,['SHAPE_Area','il_surf_de','il_surf_ca','area','AREA']);
const communeOf=(p:Props)=>prop(p,['commune','COMMUNE','municipality','MUNICIPALITE']); const dairaOf=(p:Props)=>prop(p,['daira','DAIRA']); const wilayaOf=(p:Props)=>prop(p,['wilaya','WILAYA','province','PROVINCE']);
const DAIRA_BY_COMMUNE:Record<string,string>={'Ain Touila':'Ain Touila',"M'Toussa":'Ain Touila','Babar':'Babar','Bouhmama':'Bouhmama','Chelia':'Bouhmama','Chechar':'Chechar','Djellal':'Chechar','El Ouldja':'Chechar','Khirane':'Chechar','Khenchela':'Khenchela','El Hamma':'El Hamma','Baghai':'El Hamma','Ensigha':'El Hamma','Tamza':'El Hamma','Kais':'Kais','Remila':'Kais','Taouzianat':'Kais','Ouled Rechache':'Ouled Rechache','El Mahmal':'Ouled Rechache','Yabous':'Bouhmama'};
const normalizeName=(v:string)=>v.trim().replace(/\s+/g,' ').replace(/’/g,"'");
function installLazyRegistry(){if(installed)return;installed=true;const proto=L.GeoJSON.prototype as any;const original=proto.addData;proto.addData=function(data:any){if(data?.type==='FeatureCollection'){if(!COLLECTIONS.includes(data))COLLECTIONS.push(data);}else if(data?.type==='Feature'){COLLECTIONS.push({type:'FeatureCollection',features:[data]});}return original.call(this,data)}}
function ringOf(g:Geometry):Position[]{if(g.type==='Polygon')return g.coordinates[0]??[];if(g.type==='LineString')return g.coordinates??[];return[];}
function boundsOf(r:Position[]):Bounds{const xs=r.map(p=>+p[0]),ys=r.map(p=>+p[1]);return{minX:Math.min(...xs),maxX:Math.max(...xs),minY:Math.min(...ys),maxY:Math.max(...ys)}}
function bboxDistance(a:Bounds,b:Bounds){const dx=a.maxX<b.minX?b.minX-a.maxX:b.maxX<a.minX?a.minX-b.maxX:0;const dy=a.maxY<b.minY?b.minY-a.maxY:b.maxY<a.minY?a.minY-b.maxY:0;return Math.hypot(dx,dy)}
function clipRing(ring:Position[],box:Bounds){const clip=(pts:Position[],inside:(p:Position)=>boolean,inter:(a:Position,b:Position)=>Position)=>{const out:Position[]=[];if(!pts.length)return out;let prev=pts[pts.length-1],pin=inside(prev);for(const cur of pts){const cin=inside(cur);if(cin&&!pin)out.push(inter(prev,cur));if(cin)out.push(cur);else if(pin)out.push(inter(prev,cur));prev=cur;pin=cin}return out};let out=ring.slice();out=clip(out,p=>+p[0]>=box.minX,(a,b)=>{const t=(box.minX-+a[0])/(+b[0]-+a[0]||1);return[box.minX,+a[1]+(+b[1]-+a[1])*t]});out=clip(out,p=>+p[0]<=box.maxX,(a,b)=>{const t=(box.maxX-+a[0])/(+b[0]-+a[0]||1);return[box.maxX,+a[1]+(+b[1]-+a[1])*t]});out=clip(out,p=>+p[1]>=box.minY,(a,b)=>{const t=(box.minY-+a[1])/(+b[1]-+a[1]||1);return[+a[0]+(+b[0]-+a[0])*t,box.minY]});out=clip(out,p=>+p[1]<=box.maxY,(a,b)=>{const t=(box.maxY-+a[1])/(+b[1]-+a[1]||1);return[+a[0]+(+b[0]-+a[0])*t,box.maxY]});return out}
function currentCommune(){const input=document.querySelector<HTMLInputElement>('input[placeholder*="Commune"]');return normalizeName(input?.value??'');}
function findSelectedFromDom():Parcel|null{const body=document.body.innerText;const sm=body.match(/Section numero\s*:\s*([^\n]+)/i),im=body.match(/Ilot numero\s*:\s*([^\n]+)/i);if(!sm||!im)return null;const s=digits(sm[1]),i=digits(im[1]);for(const fc of COLLECTIONS){const hit=fc.features.find(f=>digits(sectionOf((f.properties??{}) as Props))===s&&digits(ilotOf((f.properties??{}) as Props))===i);if(hit)return hit as Parcel}return null}
function adminFor(parcel:Parcel):CadastralAdminLight{const p=(parcel.properties??{}) as Props;const commune=normalizeName(communeOf(p)||currentCommune()||'Khenchela');return{commune,daira:normalizeName(dairaOf(p)||DAIRA_BY_COMMUNE[commune]||'—'),wilaya:normalizeName(wilayaOf(p)||'Khenchela')};}
export function TopographieWithPlanPreview(){const[open,setOpen]=useState(false),[selected,setSelected]=useState<Parcel|null>(null),[neighbors,setNeighbors]=useState<CadastralNeighborLight[]>([]),[admin,setAdmin]=useState<CadastralAdminLight>({commune:'Khenchela',daira:'—',wilaya:'Khenchela'});
useEffect(()=>{installLazyRegistry();const onClick=(event:MouseEvent)=>{const target=event.target as HTMLElement|null,button=target?.closest('button');if(!button||!button.textContent?.toLowerCase().includes('extrait du plan'))return;const parcel=findSelectedFromDom();if(!parcel)return;const ring=ringOf(parcel.geometry);if(ring.length<3)return;const sb=boundsOf(ring),padX=Math.max(.0002,(sb.maxX-sb.minX)*.28),padY=Math.max(.0002,(sb.maxY-sb.minY)*.28),context={minX:sb.minX-padX,maxX:sb.maxX+padX,minY:sb.minY-padY,maxY:sb.maxY+padY},sec=digits(sectionOf((parcel.properties??{}) as Props));const candidates:{f:Parcel;ring:Position[];distance:number}[]=[];for(const fc of COLLECTIONS){for(const f0 of fc.features){const f=f0 as Parcel;if(f===parcel||digits(sectionOf((f.properties??{}) as Props))!==sec)continue;const r=ringOf(f.geometry);if(r.length<3)continue;candidates.push({f,ring:r,distance:bboxDistance(sb,boundsOf(r))})}}candidates.sort((a,b)=>a.distance-b.distance);const nv=candidates.slice(0,4).map((x,idx)=>({id:`neighbor-${idx}`,ilot:ilotOf((x.f.properties??{}) as Props)||`N${idx+1}`,section:sectionOf((x.f.properties??{}) as Props)||undefined,coordinates:clipRing(x.ring,context)})).filter(n=>n.coordinates.length>=2);setSelected(parcel);setNeighbors(nv);setAdmin(adminFor(parcel));setOpen(true)};document.addEventListener('click',onClick);return()=>document.removeEventListener('click',onClick)},[]);
const p=(selected?.properties??{}) as Props;return<><TopographiePage/><CadastralPlanPreviewLight open={open} onClose={()=>setOpen(false)} admin={admin} section={sectionOf(p)} ilot={ilotOf(p)} surface={areaOf(p)} selectedRing={selected?ringOf(selected.geometry):[]} neighbors={neighbors}/></>}
