import { useEffect } from 'react';
import { CadastralPlanFinal, type CadastralAdmin, type CadastralNeighbor } from './CadastralPlanFinal';
import type { Position } from 'geojson';

type Props={open:boolean;onClose:()=>void;commune:string;section:string;ilot:string;surface:string;selectedRing:Position[];neighbors:CadastralNeighbor[];admin?:Partial<CadastralAdmin>;onExport?:(f:'dxf'|'dwg')=>void};
function hAreCa(value:string){const m=Number(String(value).replace(',','.'));if(!Number.isFinite(m))return{h:0,a:0,ca:0};const total=Math.round(m);return{h:Math.floor(total/10000),a:Math.floor((total%10000)/100),ca:total%100};}
export function CadastralPlanAreaOverlay(props:Props){
 const {open,surface,ilot}=props;const units=hAreCa(surface);
 useEffect(()=>{if(!open)return;const inject=()=>{const sheet=document.getElementById('cadastral-final-sheet');if(!sheet)return;let el=document.getElementById('cadastral-area-table');if(!el){el=document.createElement('div');el.id='cadastral-area-table';sheet.appendChild(el);}el.setAttribute('style','position:absolute;left:4%;bottom:6%;width:24%;font-family:Arial,sans-serif;background:#fff;border:1px solid #334155;z-index:30;');el.innerHTML=`<div style="font-size:7px;font-weight:700;text-transform:uppercase;letter-spacing:.04em;padding:3px 5px;border-bottom:1px solid #334155">Superficie cadastrale</div><table style="width:100%;border-collapse:collapse;font-size:7px;text-align:center"><thead><tr><th style="border-right:1px solid #64748b;padding:2px">Ilot</th><th style="border-right:1px solid #64748b;padding:2px">ha</th><th style="border-right:1px solid #64748b;padding:2px">a</th><th style="padding:2px">ca</th></tr></thead><tbody><tr><td style="border-top:1px solid #64748b;border-right:1px solid #64748b;padding:2px;font-weight:700">${ilot}</td><td style="border-top:1px solid #64748b;border-right:1px solid #64748b;padding:2px">${units.h}</td><td style="border-top:1px solid #64748b;border-right:1px solid #64748b;padding:2px">${units.a}</td><td style="border-top:1px solid #64748b;padding:2px">${units.ca}</td></tr></tbody></table><div style="font-size:6px;text-align:right;padding:2px 4px;color:#475569">${Math.round(Number(String(surface).replace(',','.'))).toLocaleString('fr-FR')} m²</div>`;};inject();const mo=new MutationObserver(inject);mo.observe(document.body,{childList:true,subtree:true});return()=>mo.disconnect();},[open,surface,ilot,units.h,units.a,units.ca]);
 return <CadastralPlanFinal {...props}/>;
}
