import { useMemo, useState } from 'react';
import { Download, FileImage, FileText, Maximize2, Minimize2, RotateCcw, Ruler, Settings2, X } from 'lucide-react';
import type { Position } from 'geojson';
import { extractCharacteristicPoints } from '../lib/cadastralPlan';

export type CadastralNeighbor = { id:string; ilot:string; section?:string; coordinates:Position[] };
type Paper='A4'|'A3'|'A2'|'A1'|'A0';
type Orientation='portrait'|'landscape';
type XY={x:number;y:number};
const PAPER_MM:Record<Paper,[number,number]>={A4:[210,297],A3:[297,420],A2:[420,594],A1:[594,841],A0:[841,1189]};
const SCALES=[200,500,1000,2000,2500,5000,10000];
const UTM_EPSG='WGS84 / UTM 32N';

function lonLatToUtm32(lon:number,lat:number):XY{
  const a=6378137,e=0.0818191908426,k0=0.9996,lon0=9*Math.PI/180,rad=Math.PI/180;
  const p=lat*rad,l=lon*rad;const N=a/Math.sqrt(1-e*e*Math.sin(p)**2);const T=Math.tan(p)**2;const C=(e*e/(1-e*e))*Math.cos(p)**2;const A=Math.cos(p)*(l-lon0);
  const M=a*((1-e*e/4-3*e**4/64-5*e**6/256)*p-(3*e*e/8+3*e**4/32+45*e**6/1024)*Math.sin(2*p)+(15*e**4/256+45*e**6/1024)*Math.sin(4*p)-(35*e**6/3072)*Math.sin(6*p));
  const x=500000+k0*N*(A+(1-T+C)*A**3/6+(5-18*T+T*T+72*C-58*(e*e/(1-e*e)))*A**5/120);
  const y=k0*(M+N*Math.tan(p)*(A*A/2+(5-T+9*C+4*C*C)*A**4/24+(61-58*T+T*T+600*C-330*(e*e/(1-e*e)))*A**6/720));
  return {x,y:y<0?y+10000000:y};
}
function isLonLat(p:Position){return Math.abs(Number(p[0]))<=180&&Math.abs(Number(p[1]))<=90;}
function toUtmRing(r:Position[]):Position[]{return r.map(p=>{if(!isLonLat(p))return p;const u=lonLatToUtm32(Number(p[0]),Number(p[1]));return[u.x,u.y]});}
function boundsOf(rings:Position[][]){const pts=rings.flat();const xs=pts.map(p=>Number(p[0])),ys=pts.map(p=>Number(p[1]));return{minX:Math.min(...xs),maxX:Math.max(...xs),minY:Math.min(...ys),maxY:Math.max(...ys)}}
function projectPoints(points:Position[],box:ReturnType<typeof boundsOf>){const dx=Math.max(1e-9,box.maxX-box.minX),dy=Math.max(1e-9,box.maxY-box.minY);return points.map(p=>({x:16+((Number(p[0])-box.minX)/dx)*68,y:16+(1-(Number(p[1])-box.minY)/dy)*68}))}
function polygonPath(points:Position[],box:ReturnType<typeof boundsOf>){return projectPoints(points,box).map((p,i)=>`${i?'L':'M'} ${p.x} ${p.y}`).join(' ')+' Z'}
function niceStep(span:number,target=5){const raw=span/Math.max(2,target),pow=10**Math.floor(Math.log10(raw)),n=raw/pow;return (n<=1?1:n<=2?2:n<=5?5:10)*pow}
function formatCoord(v:number){return Math.round(v).toLocaleString('fr-FR').replace(/\u202f/g,' ')}
function gridValues(min:number,max:number,target=5){const step=niceStep(max-min,target);const first=Math.ceil(min/step)*step;const values:number[]=[];for(let v=first;v<=max+step*.001&&values.length<8;v+=step)values.push(v);return{step,values}}

export function CadastralPlanPreview({open,onClose,commune,section,ilot,surface,selectedRing,neighbors,onExport}:{open:boolean;onClose:()=>void;commune:string;section:string;ilot:string;surface:string;selectedRing:Position[];neighbors:CadastralNeighbor[];onExport?:(format:'dxf'|'dwg')=>void}){
  const[paper,setPaper]=useState<Paper>('A4');const[orientation,setOrientation]=useState<Orientation>('landscape');const[scale,setScale]=useState(1000);const[showCoords,setShowCoords]=useState(true);const[showNeighbors,setShowNeighbors]=useState(true);const[showCrossing,setShowCrossing]=useState(true);const[expanded,setExpanded]=useState(false);
  const selectedUtm=useMemo(()=>toUtmRing(selectedRing),[selectedRing]);const neighborUtm=useMemo(()=>neighbors.map(n=>({...n,coordinates:toUtmRing(n.coordinates)})),[neighbors]);
  const rings=useMemo(()=>[selectedUtm,...(showNeighbors?neighborUtm.map(n=>n.coordinates):[])].filter(r=>r.length>2),[selectedUtm,neighborUtm,showNeighbors]);const box=useMemo(()=>rings.length?boundsOf(rings):{minX:0,maxX:1,minY:0,maxY:1},[rings]);const selectedPath=useMemo(()=>polygonPath(selectedUtm,box),[selectedUtm,box]);
  const characteristic=useMemo(()=>extractCharacteristicPoints(selectedUtm,{minTurnDeg:25,minEdgeLengthM:2}),[selectedUtm]);const characteristicProjected=useMemo(()=>projectPoints(characteristic.map(p=>p.position),box),[characteristic,box]);const grid=useMemo(()=>({x:gridValues(box.minX,box.maxX,5),y:gridValues(box.minY,box.maxY,5)}),[box]);
  if(!open)return null;const[w,h]=PAPER_MM[paper];const paperWidth=orientation==='landscape'?h:w,paperHeight=orientation==='landscape'?w:h;const visualScale=paper==='A4'?1:paper==='A3'?1.05:paper==='A2'?1.1:paper==='A1'?1.15:1.2;const markSize=Math.max(.55,Math.min(1.25,(1000/scale)*visualScale));
  const plotX0=16,plotX1=84,plotY0=16,plotY1=84;
  return <div className="fixed inset-0 z-[5000] flex items-center justify-center bg-slate-950/70 p-4 backdrop-blur-sm"><div className={`flex ${expanded?'h-[96vh] w-[98vw]':'h-[92vh] w-[96vw]'} overflow-hidden rounded-2xl bg-slate-100 shadow-2xl`}>
    <aside className="flex w-[330px] shrink-0 flex-col border-r border-slate-200 bg-white"><div className="flex items-center justify-between border-b border-slate-200 px-5 py-4"><div><div className="text-[11px] font-bold uppercase tracking-[0.18em] text-slate-500">Extrait du plan</div><div className="mt-1 text-lg font-bold text-slate-900">Présentation cadastrale</div></div><button type="button" onClick={onClose} className="rounded-lg p-2 text-slate-500 hover:bg-slate-100"><X size={18}/></button></div>
      <div className="flex-1 space-y-5 overflow-y-auto p-5"><section><div className="mb-2 flex items-center gap-2 text-xs font-bold uppercase tracking-wide text-slate-500"><Settings2 size={14}/> Mise en page</div><div className="grid grid-cols-2 gap-2">{(['A4','A3','A2','A1','A0'] as Paper[]).map(p=><button type="button" key={p} onClick={()=>setPaper(p)} className={`rounded-lg border px-3 py-2 text-sm font-semibold ${paper===p?'border-slate-900 bg-slate-900 text-white':'border-slate-200 bg-white text-slate-700 hover:bg-slate-50'}`}>{p}</button>)}</div><div className="mt-2 grid grid-cols-2 gap-2"><button type="button" onClick={()=>setOrientation('portrait')} className={`rounded-lg border px-3 py-2 text-xs font-semibold ${orientation==='portrait'?'border-sky-600 bg-sky-50 text-sky-700':'border-slate-200'}`}>Portrait</button><button type="button" onClick={()=>setOrientation('landscape')} className={`rounded-lg border px-3 py-2 text-xs font-semibold ${orientation==='landscape'?'border-sky-600 bg-sky-50 text-sky-700':'border-slate-200'}`}>Paysage</button></div></section>
      <section><label className="mb-2 flex items-center gap-2 text-xs font-bold uppercase tracking-wide text-slate-500"><Ruler size={14}/> Échelle</label><select value={scale} onChange={e=>setScale(Number(e.target.value))} className="w-full rounded-lg border border-slate-200 bg-white px-3 py-2 text-sm font-semibold text-slate-800">{SCALES.map(s=><option key={s} value={s}>1:{s}</option>)}</select><div className="mt-2 text-xs text-slate-500">Échelle numérique 1:{scale} + échelle graphique.</div></section>
      <section className="space-y-2"><div className="mb-2 text-xs font-bold uppercase tracking-wide text-slate-500">Contenu</div><label className="flex cursor-pointer items-center justify-between rounded-lg border border-slate-200 px-3 py-2 text-sm"><span>Îlots voisins</span><input type="checkbox" checked={showNeighbors} onChange={e=>setShowNeighbors(e.target.checked)}/></label><label className="flex cursor-pointer items-center justify-between rounded-lg border border-slate-200 px-3 py-2 text-sm"><span>Coordonnées X / Y</span><input type="checkbox" checked={showCoords} onChange={e=>setShowCoords(e.target.checked)}/></label><label className="flex cursor-pointer items-center justify-between rounded-lg border border-slate-200 px-3 py-2 text-sm"><span>Croisage UTM</span><input type="checkbox" checked={showCrossing} onChange={e=>setShowCrossing(e.target.checked)}/></label></section>
      <section className="rounded-xl bg-slate-50 p-3"><div className="text-xs font-bold uppercase tracking-wide text-slate-500">Référence</div><div className="mt-2 grid grid-cols-2 gap-y-1 text-sm"><span className="text-slate-500">Commune</span><b>{commune}</b><span className="text-slate-500">Section</span><b>{section}</b><span className="text-slate-500">Ilot</span><b>{ilot}</b><span className="text-slate-500">Surface</span><b>{surface} m²</b><span className="text-slate-500">Système</span><b className="text-xs">{UTM_EPSG}</b></div></section></div>
      <div className="border-t border-slate-200 p-4"><div className="grid grid-cols-2 gap-2"><button type="button" onClick={()=>onExport?.('dxf')} className="flex items-center justify-center gap-2 rounded-xl bg-slate-900 px-3 py-2.5 text-sm font-bold text-white hover:bg-slate-800"><Download size={16}/> DXF</button><button type="button" onClick={()=>onExport?.('dwg')} className="flex items-center justify-center gap-2 rounded-xl border border-slate-300 bg-white px-3 py-2.5 text-sm font-bold text-slate-800 hover:bg-slate-50"><FileText size={16}/> DWG</button></div></div></aside>
    <main className="flex min-w-0 flex-1 flex-col"><header className="flex items-center justify-between border-b border-slate-200 bg-white px-5 py-3"><div className="flex items-center gap-3"><FileImage size={18} className="text-sky-600"/><span className="text-sm font-semibold text-slate-800">Aperçu avant export</span></div><button type="button" onClick={()=>setExpanded(v=>!v)} className="rounded-lg p-2 text-slate-500 hover:bg-slate-100">{expanded?<Minimize2 size={17}/>:<Maximize2 size={17}/>}</button></header>
      <div className="flex flex-1 items-center justify-center overflow-auto p-8"><div className="relative bg-white shadow-2xl" style={{width:`${Math.min(920,paperWidth*2.05)}px`,aspectRatio:`${paperWidth}/${paperHeight}`}}><div className="absolute inset-4 border border-slate-800"><div className="absolute inset-x-4 top-3 text-center"><div className="text-[10px] font-semibold uppercase tracking-[0.18em] text-slate-500">EXTRAIT DU PLAN CADASTRAL</div><div className="mt-1 text-base font-extrabold text-slate-900">{commune} — SECTION {section} — ILOT {ilot}</div></div>
        <svg viewBox="0 0 100 100" className="absolute inset-x-6 top-20 h-[62%] w-[calc(100%-3rem)]" preserveAspectRatio="none">
          {showCrossing&&<g stroke="#64748b" fill="#475569" strokeWidth="0.12">{grid.x.values.map((v,i)=>{const px=plotX0+((v-box.minX)/(box.maxX-box.minX||1))*(plotX1-plotX0);return <g key={`x-${i}`}><path d={`M ${px-0.9} ${plotY0} L ${px+0.9} ${plotY0} M ${px} ${plotY0-0.9} L ${px} ${plotY0+0.9} M ${px-0.9} ${plotY1} L ${px+0.9} ${plotY1} M ${px} ${plotY1-0.9} L ${px} ${plotY1+0.9}`} /><text x={px} y={plotY0-2.2} textAnchor="middle" fontSize={1.45*markSize} stroke="none">{formatCoord(v)}</text><text x={px} y={plotY1+3.7} textAnchor="middle" fontSize={1.45*markSize} stroke="none">{formatCoord(v)}</text></g>})}{grid.y.values.map((v,i)=>{const py=plotY1-((v-box.minY)/(box.maxY-box.minY||1))*(plotY1-plotY0);return <g key={`y-${i}`}><path d={`M ${plotX0-0.9} ${py} L ${plotX0+0.9} ${py} M ${plotX0} ${py-0.9} L ${plotX0} ${py+0.9} M ${plotX1-0.9} ${py} L ${plotX1+0.9} ${py} M ${plotX1} ${py-0.9} L ${plotX1} ${py+0.9}`} /><text x={plotX0-2.2} y={py+0.55} textAnchor="end" fontSize={1.45*markSize} stroke="none">{formatCoord(v)}</text><text x={plotX1+2.2} y={py+0.55} textAnchor="start" fontSize={1.45*markSize} stroke="none">{formatCoord(v)}</text></g>})}</g>}
          {showNeighbors&&neighborUtm.map(n=><path key={n.id} d={polygonPath(n.coordinates,box)} fill="none" stroke="#94a3b8" strokeWidth="0.35"/>)}
          {showNeighbors&&neighborUtm.map(n=>{const c=projectPoints(n.coordinates,box);const cx=c.reduce((s,p)=>s+p.x,0)/c.length,cy=c.reduce((s,p)=>s+p.y,0)/c.length;return <text key={`${n.id}-label`} x={cx} y={cy} textAnchor="middle" fontSize="3.2" fill="#64748b">{n.section?`${n.section}/${n.ilot}`:n.ilot}</text>})}
          <path d={selectedPath} fill="#fef3c7" stroke="#b45309" strokeWidth="0.8"/>{characteristicProjected.map((p,i)=><circle key={i} cx={p.x} cy={p.y} r="0.65" fill="#b45309"/>)}
          <text x="50" y="48" textAnchor="middle" fontSize="4.2" fontWeight="700" fill="#334155">{section}</text><text x="50" y="53" textAnchor="middle" fontSize="5.2" fontWeight="800" fill="#b45309">{ilot}</text>
          <g transform="translate(90 10)"><path d="M0 8 L3 0 L6 8 L3 6 Z" fill="#0f172a"/><text x="3" y="12" textAnchor="middle" fontSize="2.5" fontWeight="700">N</text></g>
        </svg>
        {showCoords&&<div className="absolute bottom-20 left-6 right-6 rounded border border-slate-300 bg-white/95 p-2"><div className="mb-1 text-[7px] font-bold uppercase tracking-wider text-slate-500">Tableau des points caractéristiques — X / Y</div><div className="grid grid-cols-4 gap-x-4 text-[7px] text-slate-700">{characteristic.slice(0,8).map((p,i)=><div key={i} className="flex justify-between border-b border-slate-100 py-0.5"><b>P{i+1}</b><span>{formatCoord(Number(p.position[0]))} / {formatCoord(Number(p.position[1]))}</span></div>)}</div></div>}
        <div className="absolute bottom-3 left-3 right-3 flex items-end justify-between border-t border-slate-800 pt-2 text-[7px] text-slate-600"><div><b>Échelle numérique</b><br/>1:{scale}</div><div className="flex items-center gap-1"><b>Échelle graphique</b><div className="h-2 w-24 border border-slate-800"><div className="h-full w-1/2 border-r border-slate-800"/></div><span>m</span></div><div className="text-right"><b>Présentation cadastrale</b><br/>URATEC Manager</div></div>
      </div></div></div></main></div></div>;
}
