import { useMemo, useState } from 'react';
import { Download, Printer, Ruler, Settings2, X } from 'lucide-react';
import type { Position } from 'geojson';
import { extractCharacteristicPoints } from '../lib/cadastralPlan';

export type CadastralAdmin={commune:string;daira:string;wilaya:string};
export type CadastralNeighbor={id:string;ilot:string;section?:string;coordinates:Position[]};
type Paper='A4'|'A3'|'A2'|'A1'|'A0';
type XY={x:number;y:number};
const PAPER:Record<Paper,[number,number]>={A4:[210,297],A3:[297,420],A2:[420,594],A1:[594,841],A0:[841,1189]};
const SCALES=[100,200,250,500,1000,2000,2500,5000,10000,20000];
const SCR='WGS84 / UTM 32N';
function utm(lon:number,lat:number):XY{const a=6378137,e=.0818191908426,k=.9996,lon0=9*Math.PI/180,r=Math.PI/180,p=lat*r,l=lon*r,N=a/Math.sqrt(1-e*e*Math.sin(p)**2),T=Math.tan(p)**2,C=(e*e/(1-e*e))*Math.cos(p)**2,A=Math.cos(p)*(l-lon0);const M=a*((1-e*e/4-3*e**4/64-5*e**6/256)*p-(3*e*e/8+3*e**4/32+45*e**6/1024)*Math.sin(2*p)+(15*e**4/256+45*e**6/1024)*Math.sin(4*p)-(35*e**6/3072)*Math.sin(6*p));return{x:500000+k*N*(A+(1-T+C)*A**3/6+(5-18*T+T*T+72*C-58*(e*e/(1-e*e)))*A**5/120),y:k*(M+N*Math.tan(p)*(A*A/2+(5-T+9*C+4*C*C)*A**4/24+(61-58*T+T*T+600*C-330*(e*e/(1-e*e)))*A**6/720))};}
const ringU=(r:Position[])=>r.map(p=>Math.abs(+p[0])<=180&&Math.abs(+p[1])<=90?Object.values(utm(+p[0],+p[1])) as Position:p);
const bounds=(rings:Position[][])=>{const q=rings.flat(),xs=q.map(p=>+p[0]),ys=q.map(p=>+p[1]);return{minX:Math.min(...xs),maxX:Math.max(...xs),minY:Math.min(...ys),maxY:Math.max(...ys)}};
const proj=(p:Position[],b:ReturnType<typeof bounds>)=>{const dx=Math.max(1,b.maxX-b.minX),dy=Math.max(1,b.maxY-b.minY);return p.map(v=>({x:10+(+v[0]-b.minX)/dx*80,y:10+(1-(+v[1]-b.minY)/dy)*70}));};
const path=(p:Position[],b:ReturnType<typeof bounds>)=>proj(p,b).map((q,i)=>`${i?'L':'M'}${q.x} ${q.y}`).join(' ')+' Z';
const nice=(v:number)=>{const p=10**Math.floor(Math.log10(Math.max(v,1))),n=v/p;return(n<=1?1:n<=2?2:n<=5?5:10)*p};
const areaHAC=(m:number)=>{const n=Math.max(0,Math.round(Number(m)||0));const ha=Math.floor(n/10000),a=Math.floor((n-ha*10000)/100),ca=n-ha*10000-a*100;return{ha,a,ca}};
const autoScale=(w:number,h:number,pw:number,ph:number)=>{const need=Math.max(w/Math.max(pw,1)*1000,h/Math.max(ph,1)*1000);return SCALES.find(s=>s>=need)??Math.ceil(need/500)*500};
const grid=(min:number,max:number)=>{const step=nice(Math.max(1,(max-min)/4)),start=Math.ceil(min/step)*step,v:number[]=[];for(let x=start;x<=max+step*.001&&v.length<5;x+=step)v.push(x);return v};
const fmt=(v:number)=>Math.round(v).toLocaleString('fr-FR').replace(/\u202f/g,' ');
const graphicStep=(scale:number)=>nice(Math.max(10,scale*.01));

export function CadastralPlanSheet({open,onClose,commune,section,ilot,surface,selectedRing,neighbors,admin,onExport}:{open:boolean;onClose:()=>void;commune:string;section:string;ilot:string;surface:string;selectedRing:Position[];neighbors:CadastralNeighbor[];admin:CadastralAdmin;onExport?:(f:'dxf'|'dwg')=>void}){
 const[paper,setPaper]=useState<Paper>('A4'),[landscape,setLandscape]=useState(true),[scale,setScale]=useState<number|'auto'>('auto'),[showNeighbors,setShowNeighbors]=useState(true),[showGrid,setShowGrid]=useState(true),[showCoords,setShowCoords]=useState(true);
 const sel=useMemo(()=>ringU(selectedRing),[selectedRing]);
 const ns=useMemo(()=>neighbors.slice(0,4).map(n=>({...n,coordinates:ringU(n.coordinates)})),[neighbors]);
 const rings=useMemo(()=>[sel,...(showNeighbors?ns.map(n=>n.coordinates):[])].filter(r=>r.length>2),[sel,ns,showNeighbors]);
 const b=useMemo(()=>bounds(rings),[rings]);
 const [w,h]=PAPER[paper]; const pw=landscape?h:w,ph=landscape?w:h; const auto=useMemo(()=>autoScale(b.maxX-b.minX,b.maxY-b.minY,Math.max(80,pw-60),Math.max(70,ph-105)),[b,pw,ph]); const eff=scale==='auto'?auto:scale;
 const chars=useMemo(()=>extractCharacteristicPoints(sel,{minTurnDeg:30,minEdgeLengthM:2}).slice(0,10),[sel]);
 const gx=useMemo(()=>grid(b.minX,b.maxX),[b]),gy=useMemo(()=>grid(b.minY,b.maxY),[b]);
 const area=useMemo(()=>areaHAC(Number(surface)),[surface]); const bar=graphicStep(eff)*4;
 const print=()=>window.print();
 if(!open)return null;
 return <div className="fixed inset-0 z-[5000] flex items-center justify-center bg-slate-950/70 p-4"><div className="flex h-[92vh] w-[96vw] overflow-hidden rounded-2xl bg-slate-100 shadow-2xl">
  <aside className="flex w-[330px] shrink-0 flex-col border-r bg-white print:hidden"><div className="flex items-center justify-between border-b px-5 py-4"><div><div className="text-[10px] font-bold uppercase tracking-[.18em] text-slate-500">Extrait du plan</div><div className="text-lg font-bold">Présentation cadastrale</div></div><button onClick={onClose}><X size={18}/></button></div>
   <div className="flex-1 space-y-4 overflow-auto p-5"><section><div className="mb-2 flex items-center gap-2 text-xs font-bold uppercase text-slate-500"><Settings2 size={14}/> Format</div><div className="grid grid-cols-2 gap-2">{(['A4','A3','A2','A1','A0'] as Paper[]).map(p=><button key={p} onClick={()=>setPaper(p)} className={`rounded-lg border px-3 py-2 text-sm font-semibold ${paper===p?'bg-slate-900 text-white':''}`}>{p}</button>)}</div><div className="mt-2 grid grid-cols-2 gap-2"><button onClick={()=>setLandscape(false)} className={`rounded-lg border py-2 text-xs ${!landscape?'bg-sky-50 border-sky-500':''}`}>Portrait</button><button onClick={()=>setLandscape(true)} className={`rounded-lg border py-2 text-xs ${landscape?'bg-sky-50 border-sky-500':''}`}>Paysage</button></div></section>
   <section><label className="mb-2 flex items-center gap-2 text-xs font-bold uppercase text-slate-500"><Ruler size={14}/> Échelle</label><select value={String(scale)} onChange={e=>setScale(e.target.value==='auto'?'auto':Number(e.target.value))} className="w-full rounded-lg border px-3 py-2 text-sm"><option value="auto">Automatique — 1:{auto}</option>{SCALES.map(s=><option key={s} value={s}>Manuel — 1:{s}</option>)}</select></section>
   <section className="space-y-2"><label className="flex justify-between rounded-lg border px-3 py-2 text-sm"><span>Contexte voisinage</span><input type="checkbox" checked={showNeighbors} onChange={e=>setShowNeighbors(e.target.checked)}/></label><label className="flex justify-between rounded-lg border px-3 py-2 text-sm"><span>Carroyage UTM</span><input type="checkbox" checked={showGrid} onChange={e=>setShowGrid(e.target.checked)}/></label><label className="flex justify-between rounded-lg border px-3 py-2 text-sm"><span>Tableau X / Y</span><input type="checkbox" checked={showCoords} onChange={e=>setShowCoords(e.target.checked)}/></label></section></div>
   <div className="grid grid-cols-3 gap-2 border-t p-4"><button onClick={()=>onExport?.('dxf')} className="rounded-lg bg-slate-900 py-2 text-xs font-bold text-white"><Download className="mx-auto" size={15}/></button><button onClick={()=>onExport?.('dwg')} className="rounded-lg border bg-white py-2 text-xs font-bold">DWG</button><button onClick={print} className="rounded-lg border border-sky-300 bg-sky-50 py-2 text-xs font-bold text-sky-800"><Printer className="mx-auto" size={15}/></button></div></aside>
  <main className="flex flex-1 items-center justify-center overflow-auto p-6"><div id="cadastral-plan-sheet-print" className="bg-white shadow-2xl print:shadow-none" style={{width:`${Math.min(920,pw*2.05)}px`,aspectRatio:`${pw}/${ph}`}}><div className="relative h-full border-[10px] border-white"><div className="absolute inset-1 border border-slate-800">
   <div className="absolute inset-x-4 top-3 text-center"><div className="text-[10px] font-semibold uppercase tracking-[.18em] text-slate-500">EXTRAIT DU PLAN CADASTRAL</div><div className="mt-1 text-base font-extrabold">COMMUNE DE {admin.commune.toUpperCase()}</div><div className="text-[8px] text-slate-600">Daïra : {admin.daira} • Wilaya : {admin.wilaya}</div></div>
   <div className="absolute left-5 right-5 top-16 bottom-32"><svg viewBox="0 0 100 100" className="h-full w-full">{showGrid&&<g stroke="#64748b" fill="#475569" strokeWidth=".12">{gx.map((v,i)=>{const x=10+(v-b.minX)/(b.maxX-b.minX||1)*80;return <g key={'x'+i}><path d={`M${x-1} 10h2M${x}9v2M${x-1}80h2M${x}79v2`}/><text x={x} y="7" textAnchor="middle" fontSize="1.15" stroke="none">{fmt(v)}</text></g>})}{gy.map((v,i)=>{const y=80-(v-b.minY)/(b.maxY-b.minY||1)*70;return <g key={'y'+i}><path d={`M8 ${y}h2M9 ${y-1}v2M90 ${y}h2M91 ${y-1}v2`}/><text x="6.5" y={y+.4} textAnchor="end" fontSize="1.1" stroke="none">{fmt(v)}</text></g>})}</g>}
   {showNeighbors&&ns.map(n=><path key={n.id} d={path(n.coordinates,b)} fill="none" stroke="#a8b0bb" strokeWidth=".3"/>)}
   <path d={path(sel,b)} fill="#fff3c4" stroke="#b45309" strokeWidth=".8"/>
   {proj(chars.map(p=>p.position),b).map((p,i)=><circle key={i} cx={p.x} cy={p.y} r=".5" fill="#b45309"/>)}
   <text x="50" y="47" textAnchor="middle" fontSize="4" fontWeight="700">{section}</text><text x="50" y="52" textAnchor="middle" fontSize="5" fontWeight="800" fill="#b45309">{ilot}</text><g transform="translate(90 8)"><path d="M0 8L3 0L6 8L3 6Z" fill="#0f172a"/><text x="3" y="12" textAnchor="middle" fontSize="2.5">N</text></g></svg></div>
   {showCoords&&<div className="absolute left-5 bottom-10 w-[48%] rounded border border-slate-400 bg-white"><table className="w-full border-collapse text-[6px]"><caption className="border-b py-1 text-[6px] font-bold uppercase">Tableau des points caractéristiques — {SCR}</caption><thead><tr><th className="border px-1">Point</th><th className="border px-1">X (m)</th><th className="border px-1">Y (m)</th></tr></thead><tbody>{chars.map((p,i)=><tr key={i}><td className="border px-1">P{i+1}</td><td className="border px-1">{fmt(+p.position[0])}</td><td className="border px-1">{fmt(+p.position[1])}</td></tr>)}</tbody></table></div>}
   <div className="absolute right-5 bottom-10 w-[40%] text-[6px]"><table className="w-full border-collapse"><caption className="border border-slate-400 bg-slate-50 py-1 font-bold uppercase">Identification / Surface</caption><tbody><tr><th className="border px-1 text-left">Section</th><td className="border px-1">{section}</td></tr><tr><th className="border px-1 text-left">Ilot</th><td className="border px-1 font-bold">{ilot}</td></tr><tr><th className="border px-1 text-left">Surface (H)</th><td className="border px-1">{area.ha}</td></tr><tr><th className="border px-1 text-left">Area (A)</th><td className="border px-1">{area.a}</td></tr><tr><th className="border px-1 text-left">Centiare (Ca)</th><td className="border px-1">{area.ca}</td></tr><tr><th className="border px-1 text-left">Surface totale</th><td className="border px-1">{fmt(Number(surface))} m²</td></tr></tbody></table></div>
   <div className="absolute bottom-2 left-4 right-4 flex items-end justify-between border-t border-slate-800 pt-1 text-[6px]"><div><b>Échelle numérique</b><br/>1:{eff}{scale==='auto'?' (AUTO)':''}</div><div className="text-center"><b>Échelle graphique</b><br/><span>0 — {fmt(bar/4)} — {fmt(bar/2)} — {fmt(bar*3/4)} — {fmt(bar)} m</span></div><div className="text-right"><b>SCR</b><br/>{SCR}</div></div>
  </div></div></div></main></div></div>;
}
