import { useMemo, useState } from 'react';
import { Download, Printer, Ruler, X } from 'lucide-react';
import type { Position } from 'geojson';
import { extractCharacteristicPoints } from '../lib/cadastralPlan';

export type CadastralNeighborLight={id:string;ilot:string;section?:string;coordinates:Position[]};
export type CadastralAdminLight={commune:string;daira:string;wilaya:string};
type Paper='A4'|'A3'|'A2'|'A1'|'A0';
type Orientation='portrait'|'landscape';
const PAPER:Record<Paper,[number,number]>={A4:[210,297],A3:[297,420],A2:[420,594],A1:[594,841],A0:[841,1189]};
const SCALES=[100,200,250,500,1000,2000,2500,5000,10000,20000];
const SCR='WGS84 / UTM 32N';
function areaHacare(m2:number){const v=Math.max(0,Math.round(m2));return{h:Math.floor(v/10000),a:Math.floor((v%10000)/100),ca:v%100};}
function nice(v:number){const p=10**Math.floor(Math.log10(Math.max(v,1))),n=v/p;return(n<=1?1:n<=2?2:n<=5?5:10)*p;}
function autoScale(w:number,h:number,pw:number,ph:number){const need=Math.max(w/Math.max(pw,1)*1000,h/Math.max(ph,1)*1000);return SCALES.find(s=>s>=need)??Math.ceil(need/500)*500;}
function graphicStep(scale:number){const raw=Math.max(10,scale*0.01);return nice(raw);}
function toXY(p:Position){return{x:Number(p[0]),y:Number(p[1])};}
function bounds(rings:Position[][]){const q=rings.flat(),xs=q.map(p=>+p[0]),ys=q.map(p=>+p[1]);return{minX:Math.min(...xs),maxX:Math.max(...xs),minY:Math.min(...ys),maxY:Math.max(...ys)};}
function proj(r:Position[],b:ReturnType<typeof bounds>){const dx=Math.max(1,b.maxX-b.minX),dy=Math.max(1,b.maxY-b.minY);return r.map(p=>({x:9+(+p[0]-b.minX)/dx*82,y:8+(1-(+p[1]-b.minY)/dy)*70}));}
function path(r:Position[],b:ReturnType<typeof bounds>){return proj(r,b).map((p,i)=>`${i?'L':'M'}${p.x} ${p.y}`).join(' ')+' Z';}
function fmt(v:number){return Math.round(v).toLocaleString('fr-FR').replace(/\u202f/g,' ');}

export function CadastralPlanPreviewLight({open,onClose,admin,section,ilot,surface,selectedRing,neighbors,onExport}:{open:boolean;onClose:()=>void;admin:CadastralAdminLight;section:string;ilot:string;surface:string;selectedRing:Position[];neighbors:CadastralNeighborLight[];onExport?:(f:'dxf'|'dwg')=>void}){
 const[paper,setPaper]=useState<Paper>('A4'),[orientation,setOrientation]=useState<Orientation>('landscape'),[scaleMode,setScaleMode]=useState<'auto'|number>('auto'),[showCarroyage,setShowCarroyage]=useState(true),[showNeighbors,setShowNeighbors]=useState(true),[expanded,setExpanded]=useState(false);
 const area=useMemo(()=>areaHacare(Number(surface)||0),[surface]);
 const rings=useMemo(()=>[selectedRing,...(showNeighbors?neighbors.map(n=>n.coordinates):[])].filter(r=>r.length>1),[selectedRing,neighbors,showNeighbors]);
 const b=useMemo(()=>bounds(rings.length?rings:[selectedRing]),[rings,selectedRing]);
 const[w,h]=PAPER[paper],pw=orientation==='landscape'?h:w,ph=orientation==='landscape'?w:h,plotW=Math.max(80,pw-62),plotH=Math.max(70,ph-110);const auto=useMemo(()=>autoScale(b.maxX-b.minX,b.maxY-b.minY,plotW,plotH),[b,plotW,plotH]);
 const effective=scaleMode==='auto'?auto:scaleMode;const chars=useMemo(()=>extractCharacteristicPoints(selectedRing,{minTurnDeg:30,minEdgeLengthM:2}).slice(0,10),[selectedRing]);const gp=useMemo(()=>proj(chars.map(c=>c.position),b),[chars,b]);const np=useMemo(()=>neighbors.slice(0,4).map(n=>({n,p:proj(n.coordinates,b)})),[neighbors,b]);
 const gx=useMemo(()=>{const step=nice(Math.max(1,(b.maxX-b.minX)/4)),first=Math.ceil(b.minX/step)*step,a:number[]=[];for(let v=first;v<=b.maxX+step*.001&&a.length<5;v+=step)a.push(v);return a},[b]);const gy=useMemo(()=>{const step=nice(Math.max(1,(b.maxY-b.minY)/4)),first=Math.ceil(b.minY/step)*step,a:number[]=[];for(let v=first;v<=b.maxY+step*.001&&a.length<5;v+=step)a.push(v);return a},[b]);
 const step=graphicStep(effective),barM=step*4,preview=Math.min(920,pw*2.05),barPx=Math.max(90,Math.min(210,(barM/effective)*1000*(preview/pw)));
 const print=()=>{const el=document.getElementById('cad-plan-light');if(!el)return;const w=window.open('','_blank','width=1200,height=900');if(!w)return;w.document.write(`<!doctype html><html><head><title>${admin.commune}_Section_${section}_Ilot_${ilot}</title><style>@page{size:${paper} ${orientation};margin:7mm}body{margin:0;font-family:Arial,sans-serif}#sheet{width:100%}table{border-collapse:collapse}th,td{border:1px solid #555;padding:2px 4px;font-size:8px}</style></head><body><div id="sheet">${el.outerHTML}</div><script>window.onload=()=>window.print();window.onafterprint=()=>window.close()<\/script></body></html>`);w.document.close();};
 if(!open)return null;
 return <div className="fixed inset-0 z-[5000] flex items-center justify-center bg-slate-950/70 p-4"><div className={`flex ${expanded?'h-[96vh] w-[98vw]':'h-[92vh] w-[96vw]'} overflow-hidden rounded-2xl bg-slate-100 shadow-2xl`}>
  <aside className="w-[320px] shrink-0 border-r bg-white p-4 overflow-y-auto"><div className="flex items-center justify-between mb-4"><div><div className="text-[10px] font-bold uppercase tracking-[.18em] text-slate-500">Extrait du plan</div><div className="font-bold text-lg">Présentation cadastrale</div></div><button onClick={onClose} className="p-2 rounded-lg hover:bg-slate-100"><X size={18}/></button></div>
   <div className="space-y-4 text-sm"><section><div className="text-xs font-bold uppercase text-slate-500 mb-2">Format</div><div className="grid grid-cols-2 gap-2">{(['A4','A3','A2','A1','A0'] as Paper[]).map(p=><button key={p} onClick={()=>setPaper(p)} className={`border rounded-lg py-2 font-semibold ${paper===p?'bg-slate-900 text-white':''}`}>{p}</button>)}</div><div className="grid grid-cols-2 gap-2 mt-2"><button onClick={()=>setOrientation('portrait')} className={`border rounded-lg py-2 text-xs ${orientation==='portrait'?'border-sky-600 bg-sky-50':''}`}>Portrait</button><button onClick={()=>setOrientation('landscape')} className={`border rounded-lg py-2 text-xs ${orientation==='landscape'?'border-sky-600 bg-sky-50':''}`}>Paysage</button></div></section>
   <section><label className="text-xs font-bold uppercase text-slate-500 mb-2 flex items-center gap-2"><Ruler size={14}/>Échelle</label><select value={String(scaleMode)} onChange={e=>setScaleMode(e.target.value==='auto'?'auto':Number(e.target.value))} className="w-full border rounded-lg px-3 py-2 font-semibold"><option value="auto">Automatique — 1:{auto}</option>{SCALES.map(s=><option key={s} value={String(s)}>Manuel — 1:{s}</option>)}</select></section>
   <section className="space-y-2"><label className="flex justify-between border rounded-lg px-3 py-2"><span>Contexte des ilots</span><input type="checkbox" checked={showNeighbors} onChange={e=>setShowNeighbors(e.target.checked)}/></label><label className="flex justify-between border rounded-lg px-3 py-2"><span>Carroyage UTM</span><input type="checkbox" checked={showCarroyage} onChange={e=>setShowCarroyage(e.target.checked)}/></label></section>
   <section className="rounded-xl bg-slate-50 p-3"><div className="text-xs font-bold uppercase text-slate-500 mb-2">Référence administrative</div><div className="space-y-1"><div>Commune : <b>{admin.commune}</b></div><div>Daïra : <b>{admin.daira}</b></div><div>Wilaya : <b>{admin.wilaya}</b></div><div>Section : <b>{section}</b></div><div>Ilot : <b>{ilot}</b></div></div></section>
   </div><div className="mt-4 grid grid-cols-3 gap-2"><button onClick={()=>onExport?.('dxf')} className="rounded-lg bg-slate-900 text-white py-2 text-xs font-bold"><Download size={14} className="inline mr-1"/>DXF</button><button onClick={()=>onExport?.('dwg')} className="rounded-lg border py-2 text-xs font-bold">DWG</button><button onClick={print} className="rounded-lg border border-sky-300 bg-sky-50 py-2 text-xs font-bold text-sky-800"><Printer size={14} className="inline mr-1"/>Imprimer</button></div>
  </aside>
  <main className="flex-1 overflow-auto p-6 flex items-center justify-center"><div id="cad-plan-light" className="bg-white shadow-2xl relative" style={{width:`${preview}px`,aspectRatio:`${pw}/${ph}`}}><div className="absolute inset-4 border border-slate-800">
    <div className="absolute top-3 left-4 right-4 text-center"><div className="text-[9px] font-bold uppercase tracking-[.16em] text-slate-500">EXTRAIT DU PLAN CADASTRAL</div><div className="text-base font-extrabold mt-1">{admin.commune} — SECTION {section} — ILOT {ilot}</div><div className="text-[7px] text-slate-600 mt-1">Daïra : {admin.daira} • Wilaya : {admin.wilaya}</div></div>
    <svg viewBox="0 0 100 100" className="absolute left-5 right-5 top-20 h-[58%] w-[calc(100%-2.5rem)]"><g>{showCarroyage&&<g stroke="#64748b" fill="#475569" strokeWidth=".11">{gx.map((v,i)=>{const x=9+(v-b.minX)/(b.maxX-b.minX||1)*82;return <g key={'x'+i}><path d={`M${x-1} 9h2M${x}8v2M${x-1}79h2M${x}78v2`}/><text x={x} y="7" fontSize="1.1" textAnchor="middle" stroke="none">{fmt(v)}</text><text x={x} y="83" fontSize="1.1" textAnchor="middle" stroke="none">{fmt(v)}</text></g>})}{gy.map((v,i)=>{const y=79-(v-b.minY)/(b.maxY-b.minY||1)*70;return <g key={'y'+i}><path d={`M8 ${y}h2M9 ${y-1}v2M90 ${y}h2M91 ${y-1}v2`}/><text x="6.6" y={y+.4} fontSize="1.1" textAnchor="end" stroke="none">{fmt(v)}</text><text x="93.4" y={y+.4} fontSize="1.1" textAnchor="start" stroke="none">{fmt(v)}</text></g>})}</g>}
     {showNeighbors&&np.map(({n,p})=><path key={n.id} d={p.map((q,i)=>`${i?'L':'M'}${q.x} ${q.y}`).join(' ')} fill="none" stroke="#aeb6bf" strokeWidth=".25"/>)}
     <path d={path(selectedRing,b)} fill="#fff2bf" stroke="#9a5b00" strokeWidth=".8"/>{gp.map((q,i)=><circle key={i} cx={q.x} cy={q.y} r=".5" fill="#9a5b00"/>)}<text x="50" y="46" textAnchor="middle" fontSize="4.0" fontWeight="700">{section}</text><text x="50" y="51" textAnchor="middle" fontSize="5.1" fontWeight="800" fill="#9a5b00">{ilot}</text><g transform="translate(89 10)"><path d="M0 8L3 0L6 8L3 6Z" fill="#111827"/><text x="3" y="12" textAnchor="middle" fontSize="2.5" fontWeight="700">N</text></g></g></svg>
    <div className="absolute left-6 right-6 bottom-16 flex items-end gap-3"><div className="w-[46%] border border-slate-500 bg-white"><div className="px-1.5 py-1 text-[6px] font-bold uppercase">Coordonnées — {SCR}</div><table className="w-full border-collapse text-[5.5px]"><thead><tr><th className="border px-1">N°</th><th className="border px-1">X (m)</th><th className="border px-1">Y (m)</th></tr></thead><tbody>{chars.map((c,i)=><tr key={i}><td className="border px-1">P{i+1}</td><td className="border px-1">{fmt(c.position[0] as number)}</td><td className="border px-1">{fmt(c.position[1] as number)}</td></tr>)}</tbody></table></div><div className="w-[24%] border border-slate-500 bg-white"><div className="px-1.5 py-1 text-[6px] font-bold uppercase">Surface</div><table className="w-full border-collapse text-[5.5px]"><thead><tr><th className="border px-1">Ilot</th><th className="border px-1">Ha</th><th className="border px-1">A</th><th className="border px-1">Ca</th></tr></thead><tbody><tr><td className="border px-1 font-bold">{ilot}</td><td className="border px-1">{area.h}</td><td className="border px-1">{area.a}</td><td className="border px-1">{area.ca}</td></tr></tbody></table></div></div>
    <div className="absolute left-4 right-4 bottom-2 border-t border-slate-800 pt-1 flex items-end justify-between text-[6px] text-slate-700"><div><b>Échelle numérique</b><br/>1:{effective}</div><div className="text-center"><b>Échelle graphique</b><div className="mt-0.5 h-2 border-t-2 border-slate-800 relative" style={{width:`${barPx}px`}}><span className="absolute left-0 top-0 h-2 border-l-2 border-slate-800"/><span className="absolute left-1/2 top-0 h-2 border-l-2 border-slate-800"/><span className="absolute right-0 top-0 h-2 border-r-2 border-slate-800"/></div><div className="flex justify-between" style={{width:`${barPx}px`}}><span>0</span><span>{fmt(barM/2)}</span><span>{fmt(barM)} m</span></div></div><div className="text-right"><b>{SCR}</b><br/>{admin.commune} • {section}/{ilot}</div></div>
  </div></div></main></div></div>;
}
