import { useMemo, useState } from 'react';
import { Download, FileImage, FileText, Maximize2, Minimize2, Printer, Ruler, Settings2, X } from 'lucide-react';
import type { Position } from 'geojson';
import { extractCharacteristicPoints } from '../lib/cadastralPlan';

export type CadastralNeighbor = { id:string; ilot:string; section?:string; coordinates:Position[] };
export type CadastralAdmin = { commune:string; daira:string; wilaya:string };
type Paper='A4'|'A3'|'A2'|'A1'|'A0';
type Orientation='portrait'|'landscape';
type XY={x:number;y:number};
const PAPER_MM:Record<Paper,[number,number]>={A4:[210,297],A3:[297,420],A2:[420,594],A1:[594,841],A0:[841,1189]};
const SCALE_CHOICES=[100,200,250,500,1000,2000,2500,5000,10000,20000];
const UTM_EPSG='WGS84 / UTM 32N';

function lonLatToUtm32(lon:number,lat:number):XY{const a=6378137,e=0.0818191908426,k0=.9996,lon0=9*Math.PI/180,rad=Math.PI/180,p=lat*rad,l=lon*rad,N=a/Math.sqrt(1-e*e*Math.sin(p)**2),T=Math.tan(p)**2,C=(e*e/(1-e*e))*Math.cos(p)**2,A=Math.cos(p)*(l-lon0);const M=a*((1-e*e/4-3*e**4/64-5*e**6/256)*p-(3*e*e/8+3*e**4/32+45*e**6/1024)*Math.sin(2*p)+(15*e**4/256+45*e**6/1024)*Math.sin(4*p)-(35*e**6/3072)*Math.sin(6*p));const x=500000+k0*N*(A+(1-T+C)*A**3/6+(5-18*T+T*T+72*C-58*(e*e/(1-e*e)))*A**5/120);const y=k0*(M+N*Math.tan(p)*(A*A/2+(5-T+9*C+4*C*C)*A**4/24+(61-58*T+T*T+600*C-330*(e*e/(1-e*e)))*A**6/720));return{x,y:y<0?y+1e7:y};}
function toUtmRing(r:Position[]){return r.map(p=>Math.abs(Number(p[0]))<=180&&Math.abs(Number(p[1]))<=90?(()=>{const u=lonLatToUtm32(Number(p[0]),Number(p[1]));return[u.x,u.y] as Position})():p);}
function boundsOf(rings:Position[][]){const pts=rings.flat(),xs=pts.map(p=>Number(p[0])),ys=pts.map(p=>Number(p[1]));return{minX:Math.min(...xs),maxX:Math.max(...xs),minY:Math.min(...ys),maxY:Math.max(...ys)}}
function projectPoints(points:Position[],box:ReturnType<typeof boundsOf>){const dx=Math.max(1e-9,box.maxX-box.minX),dy=Math.max(1e-9,box.maxY-box.minY);return points.map(p=>({x:9+((Number(p[0])-box.minX)/dx)*82,y:9+(1-(Number(p[1])-box.minY)/dy)*72}));}
function polygonPath(points:Position[],box:ReturnType<typeof boundsOf>){return projectPoints(points,box).map((p,i)=>`${i?'L':'M'} ${p.x} ${p.y}`).join(' ')+' Z';}
function nice(v:number){const p=10**Math.floor(Math.log10(Math.max(v,1))),n=v/p;return(n<=1?1:n<=2?2:n<=5?5:10)*p;}
function autoScale(w:number,h:number,pw:number,ph:number){const need=Math.max(w/Math.max(pw,1)*1000,h/Math.max(ph,1)*1000);return SCALE_CHOICES.find(s=>s>=need)??Math.ceil(need/500)*500;}
function graphicStep(scale:number){return nice(Math.max(10,scale*.045));}
function formatM(v:number){return Math.round(v).toLocaleString('fr-FR').replace(/\u202f/g,' ');}
function gridValues(min:number,max:number){const span=Math.max(1,max-min),step=nice(span/4),first=Math.ceil(min/step)*step,values:number[]=[];for(let v=first;v<=max+step*.001&&values.length<6;v+=step)values.push(v);return values;}

export function CadastralPlanPreviewPro({open,onClose,commune,section,ilot,surface,selectedRing,neighbors,admin,onExport}:{open:boolean;onClose:()=>void;commune:string;section:string;ilot:string;surface:string;selectedRing:Position[];neighbors:CadastralNeighbor[];admin?:Partial<CadastralAdmin>;onExport?:(format:'dxf'|'dwg')=>void}){
 const[paper,setPaper]=useState<Paper>('A4'),[orientation,setOrientation]=useState<Orientation>('landscape'),[scale,setScale]=useState<number|'auto'>('auto'),[showCoords,setShowCoords]=useState(true),[showNeighbors,setShowNeighbors]=useState(true),[showCarroyage,setShowCarroyage]=useState(true),[expanded,setExpanded]=useState(false);
 const selected=useMemo(()=>toUtmRing(selectedRing),[selectedRing]), neigh=useMemo(()=>neighbors.map(n=>({...n,coordinates:toUtmRing(n.coordinates)})),[neighbors]);
 const rings=useMemo(()=>[selected,...(showNeighbors?neigh.map(n=>n.coordinates):[])].filter(r=>r.length>2),[selected,neigh,showNeighbors]),box=useMemo(()=>rings.length?boundsOf(rings):{minX:0,maxX:1,minY:0,maxY:1},[rings]);
 const[w,h]=PAPER_MM[paper],paperW=orientation==='landscape'?h:w,paperH=orientation==='landscape'?w:h,plotW=Math.max(80,paperW-62),plotH=Math.max(70,paperH-110),auto=useMemo(()=>autoScale(box.maxX-box.minX,box.maxY-box.minY,plotW,plotH),[box,plotW,plotH]),effective=scale==='auto'?auto:scale;
 const characteristic=useMemo(()=>extractCharacteristicPoints(selected,{minTurnDeg:30,minEdgeLengthM:2}).slice(0,12),[selected]),gridX=useMemo(()=>gridValues(box.minX,box.maxX),[box]),gridY=useMemo(()=>gridValues(box.minY,box.maxY),[box]);
 const step=graphicStep(effective), barM=step*4, previewPx=Math.min(920,paperW*2.05), barPx=Math.max(90,Math.min(210,(barM/effective)*1000*(previewPx/paperW))), half=barM/2;
 const doPrint=()=>{document.body.classList.add('printing-cadastral-plan');const done=()=>{document.body.classList.remove('printing-cadastral-plan');window.removeEventListener('afterprint',done);};window.addEventListener('afterprint',done);window.print();};
 if(!open)return null;
 return <><style>{`@media print{body.printing-cadastral-plan>*{display:none!important}body.printing-cadastral-plan #cadastral-print-sheet{display:block!important;position:absolute!important;left:0!important;top:0!important;margin:0!important;background:#fff!important;box-shadow:none!important;width:100%!important;height:auto!important}.cadastral-print-controls{display:none!important}}`}</style><div className="fixed inset-0 z-[5000] flex items-center justify-center bg-slate-950/70 p-4 print:bg-white"><div className={`flex ${expanded?'h-[96vh] w-[98vw]':'h-[92vh] w-[96vw]'} overflow-hidden rounded-2xl bg-slate-100 shadow-2xl`}>
  <aside className="cadastral-print-controls flex w-[335px] shrink-0 flex-col border-r border-slate-200 bg-white"><div className="flex items-center justify-between border-b border-slate-200 px-5 py-4"><div><div className="text-[11px] font-bold uppercase tracking-[0.18em] text-slate-500">Extrait du plan</div><div className="mt-1 text-lg font-bold text-slate-900">Présentation cadastrale</div></div><button type="button" onClick={onClose} className="rounded-lg p-2 text-slate-500 hover:bg-slate-100"><X size={18}/></button></div>
  <div className="flex-1 space-y-5 overflow-y-auto p-5"><section><div className="mb-2 flex items-center gap-2 text-xs font-bold uppercase tracking-wide text-slate-500"><Settings2 size={14}/> Mise en page</div><div className="grid grid-cols-2 gap-2">{(['A4','A3','A2','A1','A0'] as Paper[]).map(p=><button type="button" key={p} onClick={()=>setPaper(p)} className={`rounded-lg border px-3 py-2 text-sm font-semibold ${paper===p?'border-slate-900 bg-slate-900 text-white':'border-slate-200 bg-white text-slate-700'}`}>{p}</button>)}</div><div className="mt-2 grid grid-cols-2 gap-2"><button type="button" onClick={()=>setOrientation('portrait')} className={`rounded-lg border px-3 py-2 text-xs font-semibold ${orientation==='portrait'?'border-sky-600 bg-sky-50 text-sky-700':'border-slate-200'}`}>Portrait</button><button type="button" onClick={()=>setOrientation('landscape')} className={`rounded-lg border px-3 py-2 text-xs font-semibold ${orientation==='landscape'?'border-sky-600 bg-sky-50 text-sky-700':'border-slate-200'}`}>Paysage</button></div></section>
  <section><label className="mb-2 flex items-center gap-2 text-xs font-bold uppercase tracking-wide text-slate-500"><Ruler size={14}/> Échelle</label><select value={String(scale)} onChange={e=>setScale(e.target.value==='auto'?'auto':Number(e.target.value))} className="w-full rounded-lg border border-slate-200 bg-white px-3 py-2 text-sm font-semibold"><option value="auto">Automatique — 1:{auto}</option>{SCALE_CHOICES.map(s=><option key={s} value={String(s)}>Manuel — 1:{s}</option>)}</select></section>
  <section className="space-y-2"><div className="mb-2 text-xs font-bold uppercase tracking-wide text-slate-500">Contenu</div><label className="flex items-center justify-between rounded-lg border px-3 py-2 text-sm"><span>Ilots voisins — contexte</span><input type="checkbox" checked={showNeighbors} onChange={e=>setShowNeighbors(e.target.checked)}/></label><label className="flex items-center justify-between rounded-lg border px-3 py-2 text-sm"><span>Tableau X / Y</span><input type="checkbox" checked={showCoords} onChange={e=>setShowCoords(e.target.checked)}/></label><label className="flex items-center justify-between rounded-lg border px-3 py-2 text-sm"><span>Carroyage UTM</span><input type="checkbox" checked={showCarroyage} onChange={e=>setShowCarroyage(e.target.checked)}/></label></section>
  <section className="rounded-xl bg-slate-50 p-3 text-sm"><div className="text-xs font-bold uppercase tracking-wide text-slate-500">Informations administratives</div><div className="mt-2 space-y-1"><div><span className="text-slate-500">Commune :</span> <b>{admin?.commune||commune}</b></div><div><span className="text-slate-500">Daïra :</span> <b>{admin?.daira||'—'}</b></div><div><span className="text-slate-500">Wilaya :</span> <b>{admin?.wilaya||'Khenchela'}</b></div><div><span className="text-slate-500">Section :</span> <b>{section}</b></div><div><span className="text-slate-500">Ilot :</span> <b>{ilot}</b></div><div><span className="text-slate-500">Surface :</span> <b>{surface} m²</b></div><div><span className="text-slate-500">SCR :</span> <b>{UTM_EPSG}</b></div></div></section></div>
  <div className="cadastral-print-controls border-t border-slate-200 p-4 grid grid-cols-3 gap-2"><button type="button" onClick={()=>onExport?.('dxf')} className="flex items-center justify-center gap-2 rounded-xl bg-slate-900 px-2 py-2.5 text-xs font-bold text-white"><Download size={15}/>DXF</button><button type="button" onClick={()=>onExport?.('dwg')} className="flex items-center justify-center gap-2 rounded-xl border bg-white px-2 py-2.5 text-xs font-bold"><FileText size={15}/>DWG</button><button type="button" onClick={doPrint} className="flex items-center justify-center gap-2 rounded-xl border border-sky-300 bg-sky-50 px-2 py-2.5 text-xs font-bold text-sky-800"><Printer size={15}/>Imprimer</button></div></aside>
  <main className="flex min-w-0 flex-1 flex-col"><header className="cadastral-print-controls flex items-center justify-between border-b bg-white px-5 py-3"><div className="flex items-center gap-3"><FileImage size={18} className="text-sky-600"/><span className="text-sm font-semibold">Aperçu avant export</span></div><button type="button" onClick={()=>setExpanded(v=>!v)} className="rounded-lg p-2 text-slate-500">{expanded?<Minimize2 size={17}/>:<Maximize2 size={17}/>}</button></header>
  <div className="flex flex-1 items-center justify-center overflow-auto p-8"><div id="cadastral-print-sheet" className="cadastral-print-sheet relative bg-white shadow-2xl" style={{width:`${previewPx}px`,aspectRatio:`${paperW}/${paperH}`}}><div className="absolute inset-4 border border-slate-800">
   <div className="absolute inset-x-4 top-3 text-center"><div className="text-[10px] font-semibold uppercase tracking-[0.18em] text-slate-500">EXTRAIT DU PLAN CADASTRAL</div><div className="mt-1 text-base font-extrabold text-slate-900">{admin?.commune||commune} — SECTION {section} — ILOT {ilot}</div><div className="text-[8px] text-slate-500">Daïra : {admin?.daira||'—'} • Wilaya : {admin?.wilaya||'Khenchela'}</div></div>
   <svg viewBox="0 0 100 100" className="absolute inset-x-6 top-24 h-[59%] w-[calc(100%-3rem)]"><rect x="0" y="0" width="100" height="100" fill="white" opacity="0"/>{showCarroyage&&<g stroke="#64748b" fill="#475569" strokeWidth="0.12">{gridX.map((v,i)=>{const px=9+((v-box.minX)/(box.maxX-box.minX||1))*82;return <g key={'x'+i}><path d={`M${px-1} 9h2M${px}8v2M${px-1}81h2M${px}80v2`}/><text x={px} y="7" textAnchor="middle" fontSize="1.2" stroke="none">{formatM(v)}</text><text x={px} y="85" textAnchor="middle" fontSize="1.2" stroke="none">{formatM(v)}</text></g>})}{gridY.map((v,i)=>{const py=81-((v-box.minY)/(box.maxY-box.minY||1))*72;return <g key={'y'+i}><path d={`M8 ${py}h2M9 ${py-1}v2M90 ${py}h2M91 ${py-1}v2`}/><text x="6.8" y={py+.45} textAnchor="end" fontSize="1.15" stroke="none">{formatM(v)}</text><text x="93.2" y={py+.45} textAnchor="start" fontSize="1.15" stroke="none">{formatM(v)}</text></g>})}</g>}
   {showNeighbors&&neigh.map(n=><path key={n.id} d={polygonPath(n.coordinates,box)} fill="none" stroke="#a8b0bb" strokeWidth="0.3"/>)}{showNeighbors&&neigh.map(n=>{const c=projectPoints(n.coordinates,box);const cx=c.reduce((s,p)=>s+p.x,0)/c.length,cy=c.reduce((s,p)=>s+p.y,0)/c.length;return <text key={n.id+'t'} x={cx} y={cy} textAnchor="middle" fontSize="2.1" fill="#7b8794">{n.section?`${n.section}/${n.ilot}`:n.ilot}</text>})}
   <path d={polygonPath(selected,box)} fill="#fff3c4" stroke="#b45309" strokeWidth=".8"/>{projectPoints(characteristic.map(p=>p.position),box).map((p,i)=><circle key={i} cx={p.x} cy={p.y} r=".55" fill="#b45309"/>)}<text x="50" y="47" textAnchor="middle" fontSize="4.1" fontWeight="700" fill="#334155">{section}</text><text x="50" y="52" textAnchor="middle" fontSize="5.1" fontWeight="800" fill="#b45309">{ilot}</text><g transform="translate(89 10)"><path d="M0 8L3 0L6 8L3 6Z" fill="#0f172a"/><text x="3" y="12" textAnchor="middle" fontSize="2.5" fontWeight="700">N</text></g></svg>
   {showCoords&&<div className="absolute bottom-16 left-8 right-8 rounded border border-slate-400 bg-white px-2 py-1.5"><table className="w-full border-collapse text-[6px]"><thead><tr><th className="border px-1 py-0.5 text-left">Point</th><th className="border px-1 py-0.5 text-left">X (m)</th><th className="border px-1 py-0.5 text-left">Y (m)</th></tr></thead><tbody>{characteristic.slice(0,8).map((p,i)=><tr key={i}><td className="border px-1 py-0.5">P{i+1}</td><td className="border px-1 py-0.5">{formatM(Number(p.position[0]))}</td><td className="border px-1 py-0.5">{formatM(Number(p.position[1]))}</td></tr>)}</tbody></table></div>}
   <div className="absolute bottom-2 left-3 right-3 flex items-end justify-between border-t border-slate-800 pt-1.5 text-[6px] text-slate-700"><div><b>Échelle numérique</b><br/>1:{effective}{scale==='auto'?' (AUTO)':''}</div><div className="flex flex-col items-center"><b>Échelle graphique</b><div className="relative mt-0.5" style={{width:`${barPx}px`,height:'12px'}}><div className="absolute left-0 right-0 top-5 border-t-2 border-slate-800"/><div className="absolute left-0 top-2 h-4 border-l-2 border-slate-800"/><div className="absolute left-1/2 top-2 h-4 border-l-2 border-slate-800"/><div className="absolute right-0 top-2 h-4 border-r-2 border-slate-800"/></div><div className="flex justify-between text-[6px]" style={{width:`${barPx}px`}}><span>0</span><span>{formatM(half)}</span><span>{formatM(barM)} m</span></div></div><div className="text-right"><b>SCR</b><br/>{UTM_EPSG}</div></div>
  </div></div></div></main></div></div></>;
}
