import L from 'leaflet';

type XY={x:number;y:number};
type LL=[number,number];
type FeatureLike={type:string;geometry:{type:string;coordinates:any};properties?:Record<string,unknown>};
type PaperId='A4'|'A3'|'A2'|'A1'|'A0';
type Orientation='auto'|'landscape'|'portrait';
type Paper={id:PaperId;w:number;h:number};

const PAPERS:Paper[]=[
 {id:'A4',w:297,h:210},{id:'A3',w:420,h:297},{id:'A2',w:594,h:420},{id:'A1',w:841,h:594},{id:'A0',w:1189,h:841}
];
const CONVENTIONAL_SCALES=[500,1000,2000,5000,10000];

function prop(f:FeatureLike,keys:string[]){const p=f.properties||{};for(const k of keys){const v=p[k];if(v!==undefined&&v!==null&&String(v).trim())return String(v).trim();}return'';}
const sectionOf=(f:FeatureLike)=>prop(f,['se_no','se_no_nat','section','SECTION']);
const ilotOf=(f:FeatureLike)=>prop(f,['il_no','il_no_nat','ilot','ILOT']);
const sourceOf=(f:FeatureLike)=>prop(f,['source','file','filename','name']);
const digits=(v:string)=>v.replace(/\D/g,'');

function utm32(lon:number,lat:number):XY{
 const a=6378137,e2=0.0066943799901413165,k0=.9996,zone=32,l0=((zone-1)*6-180+3)*Math.PI/180,phi=lat*Math.PI/180,lam=lon*Math.PI/180;
 const ep=e2/(1-e2),N=a/Math.sqrt(1-e2*Math.sin(phi)**2),T=Math.tan(phi)**2,C=ep*Math.cos(phi)**2,A=Math.cos(phi)*(lam-l0);
 const M=a*((1-e2/4-3*e2**2/64-5*e2**3/256)*phi-(3*e2/8+3*e2**2/32+45*e2**3/1024)*Math.sin(2*phi)+(15*e2**2/256+45*e2**3/1024)*Math.sin(4*phi)-(35*e2**3/3072)*Math.sin(6*phi));
 return{x:k0*N*(A+(1-T+C)*A**3/6+(5-18*T+T*T+72*C-58*ep)*A**5/120)+500000,y:k0*(M+N*Math.tan(phi)*(A*A/2+(5-T+9*C+4*C*C)*A**4/24+(61-58*T+T*T+600*C-330*ep)*A**6/720))};
}
function ringLonLat(f:FeatureLike):LL[]{const g=f.geometry;if(!g)return[];if(g.type==='Polygon')return g.coordinates?.[0]||[];if(g.type==='MultiPolygon')return g.coordinates?.[0]?.[0]||[];if(g.type==='LineString')return g.coordinates||[];return[];}
function ringUtm(f:FeatureLike):XY[]{return ringLonLat(f).map(p=>utm32(Number(p[0]),Number(p[1])));}
function bbox(points:XY[]){const xs=points.map(p=>p.x),ys=points.map(p=>p.y);return{minX:Math.min(...xs),maxX:Math.max(...xs),minY:Math.min(...ys),maxY:Math.max(...ys)};}
function angle(a:XY,b:XY,c:XY){const ux=a.x-b.x,uy=a.y-b.y,vx=c.x-b.x,vy=c.y-b.y,nu=Math.hypot(ux,uy),nv=Math.hypot(vx,vy);if(!nu||!nv)return 0;return Math.acos(Math.max(-1,Math.min(1,(ux*vx+uy*vy)/(nu*nv))))*180/Math.PI;}
function significant(points:XY[]){if(points.length<3)return points;const closed=Math.hypot(points[0].x-points.at(-1)!.x,points[0].y-points.at(-1)!.y)<.01;const n=closed?points.length-1:points.length;const out:XY[]=[];for(let i=0;i<n;i++){if(angle(points[(i-1+n)%n],points[i],points[(i+1)%n])>=18)out.push(points[i]);}return out.length>=3?out:[points[0],points[Math.floor(n/3)],points[Math.floor(2*n/3)]];}
function area(points:XY[]){let s=0;for(let i=0;i<points.length;i++){const a=points[i],b=points[(i+1)%points.length];s+=a.x*b.y-b.x*a.y;}return Math.abs(s)/2;}
function areaParts(m2:number){const ha=Math.floor(m2/10000),are=Math.floor((m2-ha*10000)/100),ca=Math.round((m2-ha*10000-are*100)*100)/100;return{ha,are,ca};}
function neatGrid(span:number){const target=Math.max(1,Math.ceil(span/5));const bases=[100,200,500,1000,2000,5000,10000];return bases.find(x=>x>=target)||10000;}
function pageSize(p:Paper,o:Orientation){if(o==='portrait')return{w:Math.min(p.w,p.h),h:Math.max(p.w,p.h)};return{w:Math.max(p.w,p.h),h:Math.min(p.w,p.h)};}
function autoOrientation(p:Paper,spanX:number,spanY:number){return spanX>=spanY?'landscape':'portrait';}
function autoScale(p:Paper,o:Orientation,bb:{minX:number;maxX:number;minY:number;maxY:number}){const ps=pageSize(p,o);const usableW=(ps.w-80)*1000,usableH=(ps.h-55)*1000;const sx=usableW/Math.max(1,bb.maxX-bb.minX),sy=usableH/Math.max(1,bb.maxY-bb.minY);const target=Math.min(sx,sy);return CONVENTIONAL_SCALES.find(s=>target>=1/s)||CONVENTIONAL_SCALES.at(-1)!;}
function escapeHtml(s:string){return s.replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]||c));}
function formatDate(){return new Intl.DateTimeFormat('fr-FR',{day:'2-digit',month:'2-digit',year:'numeric'}).format(new Date());}
function planNumber(f:FeatureLike){const d=new Date(),stamp=`${d.getFullYear()}${String(d.getMonth()+1).padStart(2,'0')}${String(d.getDate()).padStart(2,'0')}`;return`EXT-${stamp}-${digits(sectionOf(f))||'—'}-${digits(ilotOf(f))||'—'}`;}
function niceLabel(v:number){return Math.round(v).toString();}

function tileXY(lon:number,lat:number,z:number){const n=2**z,x=(lon+180)/360*n,lr=lat*Math.PI/180,y=(1-Math.log(Math.tan(lr)+1/Math.cos(lr))/Math.PI)/2*n;return{x,y};}
function tileUrl(template:string,x:number,y:number,z:number){return template.replace('{x}',String(x)).replace('{y}',String(y)).replace('{z}',String(z));}
function satelliteInsetHtml(f:FeatureLike,boxX:number,boxY:number,boxW:number,boxH:number){
 const r=ringLonLat(f);if(r.length<3)return'';const cx=r.reduce((s,p)=>s+Number(p[0]),0)/r.length,cy=r.reduce((s,p)=>s+Number(p[1]),0)/r.length;const z=16,t=tileXY(cx,cy,z),tx=Math.floor(t.x),ty=Math.floor(t.y),base='https://mt1.google.com/vt/lyrs=s&x={x}&y={y}&z={z}';
 let html=`<div class="sat-wrap" style="left:${boxX}mm;top:${boxY}mm;width:${boxW}mm;height:${boxH}mm"><div class="sat-title">SITUATION — IMAGE SATELLITAIRE</div><div class="sat-grid">`;
 for(let dy=-1;dy<=1;dy++)for(let dx=-1;dx<=1;dx++)html+=`<img src="${tileUrl(base,tx+dx,ty+dy,z)}"/>`;
 html+=`</div><svg class="sat-arrow" viewBox="0 0 100 100" preserveAspectRatio="none"><line x1="50" y1="88" x2="50" y2="55" stroke="#dc2626" stroke-width="3"/><polygon points="50,42 43,58 57,58" fill="#dc2626"/><text x="54" y="94" fill="#dc2626" font-size="9" font-weight="700">ILOT ${escapeHtml(ilotOf(f)||'')}</text></svg></div>`;return html;
}
function neighborSegments(target:FeatureLike,all:FeatureLike[]){
 const tr=ringUtm(target);if(tr.length<3)return[];const tb=bbox(tr);const out:{name:string;points:XY[]}[]=[];
 for(const f of all){if(f===target)continue;const r=ringUtm(f);if(r.length<2)continue;const b=bbox(r);if(b.maxX<tb.minX-40||b.minX>tb.maxX+40||b.maxY<tb.minY-40||b.minY>tb.maxY+40)continue;
  let best={d:Infinity,i:0};for(let i=0;i<r.length;i++){const p=r[i];const d=Math.min(Math.abs(p.x-tb.minX),Math.abs(p.x-tb.maxX),Math.abs(p.y-tb.minY),Math.abs(p.y-tb.maxY));if(d<best.d)best={d,i};}
  if(best.d>15)return;const i=best.i,n=r.length,span=8,pts:Array<XY>=[];for(let k=-span;k<=span;k++){const p=r[(i+k+n)%n];pts.push(p);}out.push({name:ilotOf(f)||sectionOf(f)||'Voisin',points:pts});if(out.length>=6)break;
 }return out;
}
function layoutData(f:FeatureLike,commune:string,paperId:PaperId,orientation:Orientation,scaleValue:string){
 const pts=ringUtm(f),bb=bbox(pts),rawPaper=PAPERS.find(p=>p.id===paperId)!;const realOrientation=orientation==='auto'?autoOrientation(rawPaper,bb.maxX-bb.minX,bb.maxY-bb.minY):orientation;const ps=pageSize(rawPaper,realOrientation);const scale=scaleValue==='AUTO'?autoScale(rawPaper,realOrientation,bb):Number(scaleValue);const frameW=ps.w*scale/1000,frameH=ps.h*scale/1000;
 const margin=18, sidePanel=Math.min(90,ps.w*.30)*scale/1000, satW=Math.min(72,ps.w*.24)*scale/1000, satH=52*scale/1000;const usableW=frameW-2*margin-sidePanel,usableH=frameH-2*margin;const cx=(bb.minX+bb.maxX)/2,cy=(bb.minY+bb.maxY)/2;const viewport={minX:cx-usableW/2,maxX:cx+usableW/2,minY:cy-usableH/2,maxY:cy+usableH/2};return{pts,bb,paper:rawPaper,orientation:realOrientation,ps,scale,frameW,frameH,viewport,grid:Math.max(100,neatGrid(Math.max(bb.maxX-bb.minX,bb.maxY-bb.minY))),significant:significant(pts),commune,sidePanel,satW,satH,plan:planNumber(f),date:formatDate(),source:sourceOf(f)||'KMZ cadastral local — URATEC Manager'};
}
function buildPreview(f:FeatureLike,commune:string,config:{paperId:PaperId;orientation:Orientation;scale:string},all:FeatureLike[]){
 const d=layoutData(f,commune,config.paperId,config.orientation,config.scale),{ps,scale,viewport,grid}=d,pts=d.pts,sig=d.significant,neigh=neighborSegments(f,all),ap=areaParts(area(pts));
 const mmToPx=3.78;const W=ps.w,H=ps.h;const panelW=Math.min(90,W*.30),left=10,rightPanel=W-panelW-10,mainW=rightPanel-left;const vW=viewport.maxX-viewport.minX,vH=viewport.maxY-viewport.minY;const sx=(x:number)=>left+(x-viewport.minX)/vW*mainW,sy=(y:number)=>H-10-(y-viewport.minY)/vH*(H-20);const poly=pts.map(p=>`${sx(p.x)},${sy(p.y)}`).join(' ');
 const gx=Math.ceil(viewport.minX/grid)*grid,gy=Math.ceil(viewport.minY/grid)*grid;let gridSvg='';for(let x=gx;x<=viewport.maxX;x+=grid)gridSvg+=`<line x1="${sx(x)}" y1="${sy(viewport.minY)}" x2="${sx(x)}" y2="${sy(viewport.maxY)}" class="g"/><text x="${sx(x)}" y="13" class="gl">${niceLabel(x)}</text>`;for(let y=gy;y<=viewport.maxY;y+=grid)gridSvg+=`<line x1="${sx(viewport.minX)}" y1="${sy(y)}" x2="${sx(viewport.maxX)}" y2="${sy(y)}" class="g"/><text x="5" y="${sy(y)}" class="gl">${niceLabel(y)}</text>`;
 const pointSvg=sig.map((p,i)=>`<circle cx="${sx(p.x)}" cy="${sy(p.y)}" r="1.7" class="p"/><text x="${sx(p.x)+3}" y="${sy(p.y)-3}" class="pl">P${i+1}</text>`).join('');
 const neighborSvg=neigh.map(n=>{const a=n.points.map(p=>`${sx(p.x)},${sy(p.y)}`).join(' ');const m=n.points[Math.floor(n.points.length/2)];return`<polyline points="${a}" class="ng"/><text x="${sx(m.x)+3}" y="${sy(m.y)-3}" class="nl">${escapeHtml(n.name)}</text>`}).join('');
 const northX=rightPanel-12,northY=22;
 const cart=`<div class="cart"><div class="ct">EXTRAIT DU PLAN CADASTRAL</div><div>Commune : <b>${escapeHtml(commune||'—')}</b></div><div>Section : <b>${escapeHtml(sectionOf(f)||'—')}</b></div><div>Ilot : <b>${escapeHtml(ilotOf(f)||'—')}</b></div><div>Système : <b>WGS84 / UTM 32N</b></div><div>Échelle : <b>1/${scale}</b></div><div>Format : <b>${d.paper.id} ${d.orientation==='landscape'?'Paysage':'Portrait'}</b></div><div>Date : <b>${d.date}</b></div><div>N° plan : <b>${d.plan}</b></div><div>Source : <b>${escapeHtml(d.source)}</b></div><hr><div><b>Surface</b><br>${area(pts).toFixed(2)} m²<br>${ap.ha} ha ${ap.are} a ${ap.ca.toFixed(2)} ca</div><hr><div class="small"><b>Points caractéristiques</b><table><tr><th>Pt</th><th>X</th><th>Y</th></tr>${sig.map((p,i)=>`<tr><td>P${i+1}</td><td>${p.x.toFixed(2)}</td><td>${p.y.toFixed(2)}</td></tr>`).join('')}</table></div></div>`;
 const scaleBar=`<div class="scale-bar"><div><b>Échelle graphique</b></div><div class="bars"><span>0</span><i></i><span>${grid}</span><i></i><span>${grid*2}</span><i></i><span>${grid*3}</span></div><div>${grid*3} m</div></div>`;
 const sat=satelliteInsetHtml(f,rightPanel-76,H-68,66,54);
 const svg=`<svg class="map" viewBox="0 0 ${W} ${H}"><g>${gridSvg}</g><polyline points="${poly}" class="parcel"/>${neighborSvg}${pointSvg}<line x1="${northX}" y1="${northY+12}" x2="${northX}" y2="${northY+45}" class="north-line"/><polygon points="${northX},${northY+6} ${northX-4},${northY+18} ${northX+4},${northY+18}" class="north-head"/><text x="${northX-3}" y="${northY+3}" class="nt">N</text></svg>`;
 return `<div class="sheet" style="width:${W}mm;height:${H}mm"><div class="top-title">EXTRAIT DU PLAN — ${escapeHtml(sectionOf(f)||'')} / ${escapeHtml(ilotOf(f)||'')}</div>${svg}${cart}${sat}${scaleBar}<div class="foot">Carroyage UTM 32N • intervalle ${grid} m • URATEC Manager</div></div>`;
}
function dxfLine(a:XY,b:XY,layer:string='PARCELLE'){return['0','LINE','8',layer,'10',a.x.toFixed(3),'20',a.y.toFixed(3),'30','0','11',b.x.toFixed(3),'21',b.y.toFixed(3),'31','0'].join('\n');}
function dxfText(p:XY,t:string,h:number,layer='ANNOTATION'){return['0','TEXT','8',layer,'10',p.x.toFixed(3),'20',p.y.toFixed(3),'30','0','40',h.toFixed(3),'1',t].join('\n');}
function dxfPoly(p:XY[],layer='PARCELLE'){const a=['0','LWPOLYLINE','8',layer,'90',String(p.length),'70','1'];for(const q of p)a.push('10',q.x.toFixed(3),'20',q.y.toFixed(3));return a.join('\n');}
function makeDxf(f:FeatureLike,commune:string,config:{paperId:PaperId;orientation:Orientation;scale:string},all:FeatureLike[]){const d=layoutData(f,commune,config.paperId,config.orientation,config.scale),pts=d.pts,neigh=neighborSegments(f,all),out=['0','SECTION','2','HEADER','0','ENDSEC','0','SECTION','2','ENTITIES',dxfPoly(pts)];const n=d.viewport,grid=d.grid;for(let x=Math.ceil(n.minX/grid)*grid;x<=n.maxX;x+=grid){out.push(dxfLine({x,y:n.minY},{x,y:n.maxY},'CARROYAGE'),dxfText({x,y:n.maxY},`X ${Math.round(x)}`,Math.max(2,grid/500),'ANNOTATION'));}for(let y=Math.ceil(n.minY/grid)*grid;y<=n.maxY;y+=grid){out.push(dxfLine({x:n.minX,y},{x:n.maxX,y},'CARROYAGE'),dxfText({x:n.minX,y},`Y ${Math.round(y)}`,Math.max(2,grid/500),'ANNOTATION'));}for(let i=0;i<d.significant.length;i++)out.push(dxfText(d.significant[i],`P${i+1}`,Math.max(2,grid/500),'ANNOTATION'));for(const nb of neigh){for(let i=1;i<nb.points.length;i++)out.push(dxfLine(nb.points[i-1],nb.points[i],'VOISINS'));const m=nb.points[Math.floor(nb.points.length/2)];out.push(dxfText(m,nb.name,Math.max(2,grid/550),'VOISINS'));}const p={x:n.minX+20,y:n.maxY-20};out.push(dxfText(p,'EXTRAIT DU PLAN CADASTRAL',Math.max(3,grid/250)));out.push(dxfText({x:p.x,y:p.y-15},`Commune : ${commune||'—'}`),dxfText({x:p.x,y:p.y-30},`Section : ${sectionOf(f)||'—'}   Ilot : ${ilotOf(f)||'—'}`),dxfText({x:p.x,y:p.y-45},`WGS84 / UTM 32N   Echelle 1/${d.scale}`),dxfText({x:p.x,y:p.y-60},`Date : ${d.date}   N° plan : ${d.plan}`));out.push('0','ENDSEC','0','EOF');return out.join('\n')+'\n';}
function download(text:string,name:string,type:string){const blob=new Blob([text],{type});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}

function openPreview(f:FeatureLike,commune:string,all:FeatureLike[]){
 const root=document.getElementById('uratec-preview-v2');if(root)root.remove();
 let paperId:PaperId='A4',orientation:Orientation='auto',scale='AUTO';
 const rootEl=document.createElement('div');rootEl.id='uratec-preview-v2';rootEl.style.cssText='position:fixed;inset:0;z-index:100000;background:rgba(15,23,42,.72);display:flex;flex-direction:column;';document.body.appendChild(rootEl);
 const draw=()=>{const cfg={paperId,orientation,scale},d=layoutData(f,commune,paperId,orientation,scale);rootEl.innerHTML=`<div style="height:58px;display:flex;align-items:center;gap:10px;padding:10px 14px;background:#fff;border-bottom:1px solid #cbd5e1;font-family:Arial"><b style="font-size:16px;color:#0f172a">Aperçu du plan</b><span style="color:#64748b;font-size:12px">${escapeHtml(commune||'—')} • Section ${escapeHtml(sectionOf(f)||'—')} • Ilot ${escapeHtml(ilotOf(f)||'—')}</span><div style="margin-left:auto;display:flex;gap:8px;align-items:center"><label style="font-size:11px;font-weight:700">Papier<select id="pv-paper"><option>A4</option><option>A3</option><option>A2</option><option>A1</option><option>A0</option></select></label><label style="font-size:11px;font-weight:700">Orientation<select id="pv-orient"><option value="auto">Auto</option><option value="landscape">Paysage</option><option value="portrait">Portrait</option></select></label><label style="font-size:11px;font-weight:700">Échelle<select id="pv-scale"><option value="AUTO">Automatique</option>${CONVENTIONAL_SCALES.map(s=>`<option value="${s}">1/${s}</option>`).join('')}</select></label><button id="pv-export" style="background:#0284c7;color:#fff;border:0;border-radius:8px;padding:9px 13px;font-weight:700">Exporter</button><button id="pv-close" style="border:1px solid #cbd5e1;background:#fff;border-radius:8px;padding:9px 13px">Fermer</button></div></div><div id="pv-body" style="flex:1;overflow:auto;padding:18px;display:flex;justify-content:center;align-items:flex-start"></div>`;const p=rootEl.querySelector('#pv-paper') as HTMLSelectElement,o=rootEl.querySelector('#pv-orient') as HTMLSelectElement,s=rootEl.querySelector('#pv-scale') as HTMLSelectElement;p.value=paperId;o.value=orientation;s.value=scale;const body=rootEl.querySelector('#pv-body') as HTMLElement;body.innerHTML=buildPreview(f,commune,cfg,all);const sheet=body.querySelector('.sheet') as HTMLElement;sheet.style.transform='scale(.86)';sheet.style.transformOrigin='top center';sheet.style.boxShadow='0 15px 50px rgba(0,0,0,.25)';sheet.style.background='#fff';
 p.onchange=()=>{paperId=p.value as PaperId;draw();};o.onchange=()=>{orientation=o.value as Orientation;draw();};s.onchange=()=>{scale=s.value;draw();};rootEl.querySelector('#pv-close')?.addEventListener('click',()=>rootEl.remove());rootEl.querySelector('#pv-export')?.addEventListener('click',()=>showExportMenu(f,commune,all,{paperId,orientation,scale}));};
 draw();
}
function showExportMenu(f:FeatureLike,commune:string,all:FeatureLike[],cfg:{paperId:PaperId;orientation:Orientation;scale:string}){
 const old=document.getElementById('uratec-export-choice');if(old)old.remove();const wrap=document.createElement('div');wrap.id='uratec-export-choice';wrap.style.cssText='position:fixed;inset:0;z-index:100002;background:rgba(15,23,42,.35);display:flex;align-items:center;justify-content:center;font-family:Arial';const box=document.createElement('div');box.style.cssText='width:min(430px,92vw);background:#fff;border-radius:16px;padding:20px;box-shadow:0 20px 70px rgba(0,0,0,.3)';box.innerHTML=`<div style="font-size:18px;font-weight:800">Exporter le plan</div><div style="font-size:12px;color:#64748b;margin-top:4px">Le layout courant sera conservé.</div><div style="display:grid;gap:10px;margin-top:18px"><button id="ex-dxf" style="padding:11px;border:0;background:#0284c7;color:#fff;border-radius:9px;font-weight:700">Exporter DXF</button><button id="ex-pdf" style="padding:11px;border:0;background:#334155;color:#fff;border-radius:9px;font-weight:700">Imprimer / PDF — 1 page</button><button id="ex-dwg" style="padding:11px;border:1px solid #cbd5e1;background:#f8fafc;border-radius:9px;font-weight:700">DWG</button><button id="ex-cancel" style="padding:10px;border:1px solid #cbd5e1;background:#fff;border-radius:9px">Annuler</button></div><div id="ex-msg" style="font-size:12px;color:#64748b;margin-top:12px"></div>`;wrap.appendChild(box);document.body.appendChild(wrap);
 box.querySelector('#ex-cancel')?.addEventListener('click',()=>wrap.remove());
 box.querySelector('#ex-dwg')?.addEventListener('click',()=>{(box.querySelector('#ex-msg') as HTMLElement).textContent='DWG réel sera branché dans la couche Desktop/CAD. DXF actuel réel et métrique.';});
 box.querySelector('#ex-dxf')?.addEventListener('click',()=>{const d=layoutData(f,commune,cfg.paperId,cfg.orientation,cfg.scale);download(makeDxf(f,commune,cfg,all),`EXTRAIT_${digits(sectionOf(f))}_${digits(ilotOf(f))}_${d.paper.id}_1-${d.scale}.dxf`,'application/dxf');(box.querySelector('#ex-msg') as HTMLElement).textContent='DXF généré avec le layout courant.';});
 box.querySelector('#ex-pdf')?.addEventListener('click',()=>{const d=layoutData(f,commune,cfg.paperId,cfg.orientation,cfg.scale),html=`<!doctype html><html><head><meta charset="utf-8"><title>${escapeHtml(d.plan)}</title><style>@page{size:${d.orientation==='landscape'?'landscape':'portrait'};margin:0}html,body{margin:0;padding:0}.sheet{position:relative;width:${d.ps.w}mm;height:${d.ps.h}mm;overflow:hidden;background:#fff}.map{position:absolute;inset:0;width:100%;height:100%}.top-title{position:absolute;left:10mm;top:7mm;font:700 5mm Arial;z-index:4}.cart{position:absolute;right:10mm;top:10mm;width:${d.sidePanel}mm;font:3mm Arial;line-height:1.4;z-index:5;background:rgba(255,255,255,.92);padding:4mm;border:.25mm solid #333}.cart .ct{font-weight:800;font-size:4mm}.cart hr{border:0;border-top:.2mm solid #999;margin:2mm 0}.cart table{width:100%;border-collapse:collapse;font-size:2.3mm}.cart td,.cart th{border:.15mm solid #555;padding:.6mm}.small{font-size:2.5mm}.foot{position:absolute;left:10mm;bottom:5mm;font:2.5mm Arial;z-index:5}.scale-bar{position:absolute;left:10mm;bottom:10mm;font:2.6mm Arial;z-index:6;background:#fff;padding:2mm;border:.2mm solid #777}.bars{display:flex;align-items:center;gap:1mm}.bars i{display:inline-block;width:12mm;border-top:.7mm solid #111}.g{stroke:#aab2bb;stroke-width:.18}.gl{font:2.2mm Arial;fill:#475569;text-anchor:middle}.parcel{fill:none;stroke:#111;stroke-width:.7}.p{fill:#111}.pl{font:2.4mm Arial}.ng{fill:none;stroke:#64748b;stroke-width:.45}.nl{font:2.4mm Arial;fill:#334155}.north-line{stroke:#111;stroke-width:.7}.north-head{fill:#111}.nt{font:4mm Arial;font-weight:700}.sat-wrap{position:absolute;z-index:6;border:.25mm solid #333;background:#fff;padding:1mm;box-sizing:border-box}.sat-title{font:2.4mm Arial;font-weight:700;margin-bottom:1mm}.sat-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:0;overflow:hidden}.sat-grid img{width:100%;height:100%;display:block}.sat-arrow{position:absolute;inset:0;width:100%;height:100%;pointer-events:none}</style></head><body><div class="sheet">${buildPreview(f,commune,cfg,all).replace(/^<div class="sheet"[^>]*>|<\/div>$/g,'')}</div><script>window.onload=()=>setTimeout(()=>window.print(),900)</script></body></html>`;const win=window.open('','_blank');if(!win){alert('Autorisez les fenêtres contextuelles pour imprimer.');return;}win.document.open();win.document.write(html);win.document.close();});
}
function install(){const w=window as any;if(w.__uratecPreviewV2Installed)return;w.__uratecPreviewV2Installed=true;const attach=()=>{document.querySelectorAll('button').forEach(btn=>{if((btn as HTMLElement).dataset.uratecPreviewV2==='1')return;if((btn.textContent||'').toLocaleLowerCase().includes('extrait du plan')){(btn as HTMLElement).dataset.uratecPreviewV2='1';btn.addEventListener('click',ev=>{ev.preventDefault();ev.stopPropagation();const f=w.__uratecSelectedParcel as FeatureLike|null;if(!f){alert('Sélectionnez d’abord une parcelle sur la carte.');return;}const popup=document.querySelector('.leaflet-popup-content') as HTMLElement|null;const txt=popup?.innerText||'';const m=txt.match(/Commune\s*:\s*([^\n]+)/i);const all=(w.__uratecAllFeatures||[]) as FeatureLike[];openPreview(f,m?.[1]?.trim()||'',all);},true);}})};const mo=new MutationObserver(attach);mo.observe(document.body,{childList:true,subtree:true});attach();}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install,{once:true});else install();
